//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, _priv_NBSSafeMutableArray;

@interface _priv_NBSLens_webViewDataManager : NSObject
{
    _priv_NBSSafeMutableArray *jsErrors;
    _priv_NBSSafeMutableArray *pfmDatas;
    NSDictionary *private_buf_postData;
}

+ (id)singletonObject;
- (void).cxx_destruct;
- (void)logWebPerformance:(id)arg1;
- (void)logJSException:(id)arg1;
- (void)postToServer;
- (id)getPostData;
- (void)dealloc;
- (id)init;
- (void)onNotification_post:(id)arg1;
- (void)handleMemoryWarning;

@end

