//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSMutableArray, NSString;

@interface _priv_NBSLensCrashInfo : NSObject
{
    int _dev_connectType;
    int _isOKInit;
    NSString *_rpt_uuid;
    NSString *_crash_reason;
    double _crash_tm;
    double _app_start_tm;
    NSString *_app_ver;
    NSString *_app_SDK_ver;
    NSString *_dev_carrierName;
    NSString *_dev_netType;
    NSDictionary *_addtionalInfo;
    NSMutableArray *_binaryImageList;
    NSMutableArray *_backtraceList;
    NSMutableArray *_backtraceItems;
    NSString *_mainUUID;
    NSString *_systemVersion;
}

+ (id)objectFromFile:(id)arg1;
@property(retain, nonatomic) NSString *systemVersion; // @synthesize systemVersion=_systemVersion;
@property(retain) NSString *mainUUID; // @synthesize mainUUID=_mainUUID;
@property int isOKInit; // @synthesize isOKInit=_isOKInit;
@property(retain) NSMutableArray *backtraceItems; // @synthesize backtraceItems=_backtraceItems;
@property(retain) NSMutableArray *backtraceList; // @synthesize backtraceList=_backtraceList;
@property(retain) NSMutableArray *binaryImageList; // @synthesize binaryImageList=_binaryImageList;
@property(retain) NSDictionary *addtionalInfo; // @synthesize addtionalInfo=_addtionalInfo;
@property(retain) NSString *dev_netType; // @synthesize dev_netType=_dev_netType;
@property(retain) NSString *dev_carrierName; // @synthesize dev_carrierName=_dev_carrierName;
@property int dev_connectType; // @synthesize dev_connectType=_dev_connectType;
@property(retain) NSString *app_SDK_ver; // @synthesize app_SDK_ver=_app_SDK_ver;
@property(retain) NSString *app_ver; // @synthesize app_ver=_app_ver;
@property double app_start_tm; // @synthesize app_start_tm=_app_start_tm;
@property double crash_tm; // @synthesize crash_tm=_crash_tm;
@property(retain) NSString *crash_reason; // @synthesize crash_reason=_crash_reason;
@property(retain) NSString *rpt_uuid; // @synthesize rpt_uuid=_rpt_uuid;
- (void).cxx_destruct;
- (void)fromDict:(id)arg1;
- (id)toDict;
- (void)prepare;
- (void)imgList_shrink;
- (int)indexOfImageList:(id)arg1 byAddr:(unsigned long long)arg2;
- (int)indexOfImageList:(id)arg1 byName:(id)arg2;
- (void)saveToFile:(id)arg1;
- (id)render;
- (id)render_images;
- (id)render_app;
- (id)render_dev;
- (id)render_traces;
- (id)init;

@end

