//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _priv_NBSMethodsHelper : NSObject
{
}

+ (id)connection:(id)arg1 didFailWithError:(id)arg2 sender:(id)arg3 selector:(SEL)arg4;
+ (id)connectionFinishLoading:(id)arg1 sender:(id)arg2 selector:(SEL)arg3;
+ (void)connection:(id)arg1 sendBodyData:(long long)arg2 totalBytesWritten:(long long)arg3 totalBytesExpectedToWrite:(long long)arg4;
+ (id)connection:(id)arg1 receiveData:(id)arg2 sender:(id)arg3 selector:(SEL)arg4;
+ (id)connection:(id)arg1 receiveResponse:(id)arg2 sender:(id)arg3 selector:(SEL)arg4;
+ (id)connection:(id)arg1 request:(id)arg2 redirectResponse:(id)arg3 sender:(id)arg4 selector:(SEL)arg5;

@end

