//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSNumber, NSString, _priv_NBSStack, _priv_NBSTraceItem;

@interface _priv_NBSTraceTree : NSObject
{
    NSString *threadId;
    _priv_NBSStack *stack;
    _priv_NBSTraceItem *root;
    _Bool flag;
    _Bool isAbsTime;
    _priv_NBSTraceItem *parent;
    NSNumber *parentVCS;
}

+ (id)traceTreeCopyFrom:(id)arg1;
+ (id)traceTreeWithRoot:(id)arg1;
+ (id)traceTreeWithThreadId:(id)arg1;
@property(retain, nonatomic) NSNumber *parentVCS; // @synthesize parentVCS;
@property(nonatomic) __weak _priv_NBSTraceItem *parent; // @synthesize parent;
@property(readonly) _Bool isAbsTime; // @synthesize isAbsTime;
@property(retain, nonatomic) _priv_NBSTraceItem *root; // @synthesize root;
@property(copy, nonatomic) NSString *threadId; // @synthesize threadId;
- (void).cxx_destruct;
- (_Bool)isClosed;
- (id)tailoerFrom:(long long)arg1 to:(long long)arg2;
- (void)mergeOtherTree:(id)arg1;
- (void)setIgnoreFlagByTime1:(long long)arg1 andTime2:(long long)arg2;
- (void)convertToRelTimeFrom:(long long)arg1 limitedTo:(long long)arg2;
- (void)convertTimeOfItem:(id)arg1 fromTime:(long long)arg2 limitedTo:(long long)arg3;
- (long long)finishTime;
- (long long)startTime;
- (id)renderWithStartTime:(long long)arg1;
- (id)peer;
- (id)pop;
- (void)push:(id)arg1;
- (id)init;

@end

