//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSLock.h>

@class _priv_NBSSafeMutableArray, _priv_NBSSafeMutableDictionary;

@interface _priv_NBSErrorManager : NSLock
{
    _priv_NBSSafeMutableDictionary *Errors;
    _priv_NBSSafeMutableArray *ErrList;
    _Bool busy;
    int busy_length;
    _priv_NBSSafeMutableArray *_errorUploadBuf;
}

+ (id)sharedErrorManager;
@property(retain, nonatomic) _priv_NBSSafeMutableArray *errorUploadBuf; // @synthesize errorUploadBuf=_errorUploadBuf;
@property(readonly) _priv_NBSSafeMutableArray *ErrList; // @synthesize ErrList;
@property(readonly) _priv_NBSSafeMutableDictionary *Errors; // @synthesize Errors;
- (void).cxx_destruct;
- (void)freeUploadErrorsBuf:(_Bool)arg1;
- (void)getErrorList_free:(_Bool)arg1;
- (void)addErrorsToUploadBuf:(id)arg1;
- (id)getUploadErrors;
- (id)getErrorList_busy;
- (int)getNumberWithHttpMethod:(id)arg1;
- (void)logErrorWithHTTPError:(id)arg1 Response:(id)arg2 ResponseData:(id)arg3;
- (void)logErrorWithError:(id)arg1 Request:(id)arg2;
- (void)logErrorWithException:(id)arg1 Request:(id)arg2;
- (_Bool)ignoreErrorByCode:(int)arg1 request:(id)arg2;
- (id)addErrToListForKey:(id)arg1;
- (id)getParamStrFromRequest:(id)arg1 Response:(id)arg2 ResponseData:(id)arg3 Exception:(id)arg4;
- (_Bool)findAndIncrease:(id)arg1;
- (id)getKeyFromURI:(id)arg1 urlParams:(id)arg2 statusCode:(int)arg3 httpMethod:(id)arg4;
- (void)dealloc;
- (id)init;
- (void)handleMemoryWarning;
- (void)clearAll;
- (void)clearTo:(unsigned long long)arg1;
- (void)innerClear:(unsigned long long)arg1;

@end

