//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseViewController.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class AFHTTPRequestOperation, NSString, UITableView;

@interface AccountViewController : BaseViewController <UITableViewDelegate, UITableViewDataSource>
{
    UITableView *accountTable;
    AFHTTPRequestOperation *requestCanCancel;
    long long currentBalance;
    long long currentVoucher;
    long long currentVoucherCount;
    _Bool showPayForRemitAd;
}

- (void).cxx_destruct;
- (void)progressHideWithCancelBtn;
- (void)onClickLeftItem;
- (void)goRemitAdView;
- (void)goPurchaseRecordView;
- (void)goChargeRecordView;
- (void)goVoucherRecordView;
- (void)goRechargeView;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)removeLoadingView;
- (void)addLoadingView;
- (void)startAccountInfoRequest;
- (void)viewWillAppear:(_Bool)arg1;
- (void)copyUserInfo;
- (void)addFooterView;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

