//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseViewController.h"

#import "UIActionSheetDelegate-Protocol.h"
#import "UIAlertViewDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"

@class NSString, UITextField;

@interface AddBookViewController : BaseViewController <UIAlertViewDelegate, UITextFieldDelegate, UIActionSheetDelegate>
{
    UITextField *bookNameField;
    UITextField *bookAuthorField;
    NSString *bookId;
}

- (void).cxx_destruct;
- (void)onClickFirstRightItem;
- (void)onClickLeftItem;
- (void)didReceiveMemoryWarning;
- (void)viewWillAppear:(_Bool)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)goBack;
- (void)setTextFieldProperty:(id)arg1;
- (void)setLabelProperty:(id)arg1;
- (id)createAddBookView;
- (void)showAlertMessage:(id)arg1;
- (void)parseResponse:(id)arg1;
- (void)sendRequestAsynchrounous;
- (void)createBook;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

