//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "MBProgressHUDDelegate-Protocol.h"

@class MBProgressHUD, NSArray, NSString, UIButton, UIColor, UILabel, UISegmentedControl, UIView;

@interface BaseViewController : UIViewController <MBProgressHUDDelegate>
{
    UIView *navBarView;
    UIButton *navLeftBarBtn;
    UILabel *navTitleLabel;
    UIButton *navFirstRightBarBtn;
    UIButton *navSecondRightBarBtn;
    UISegmentedControl *segmentedControl;
    NSArray *currentSegmentArray;
    int customBgTag;
    NSString *currentTitle;
    UIColor *navBarBackgroundColor;
    UIColor *navBarTextColor;
    UIColor *navBarSeparatorColor;
    UIColor *navItemNormalColor;
    UIColor *navItemHighlightedColor;
    MBProgressHUD *progress;
    _Bool backGestureEnabled;
    UIView *_shadowView;
}

@property(retain, nonatomic) UIView *shadowView; // @synthesize shadowView=_shadowView;
- (void).cxx_destruct;
- (void)refreshAllSubviews;
- (void)progressHideWithCancelBtn;
- (void)hudWasHiddenByCancelBtn;
- (void)updateProgressText:(id)arg1;
- (void)bringProgressToFront;
- (void)hideProgressWithMsg:(id)arg1;
- (void)hideProgress;
- (void)showProgressWithMsg:(id)arg1 cancelBtn:(_Bool)arg2;
- (void)showProgress;
- (void)onClickSegment:(id)arg1;
- (void)onClickSecondRightItem;
- (void)onClickFirstRightItem;
- (void)onClickLeftItem;
- (_Bool)backGestureEnabled;
- (void)disableBackGesture;
- (void)enableBackGesture;
- (void)adaptSecondRightItemWithNormalImage:(id)arg1 highlightedImage:(id)arg2;
- (void)adaptSecondRightItemWithTitle:(id)arg1;
- (void)setFirstRightItemEnabled:(_Bool)arg1;
- (void)adaptFirstRightItemWithNormalImage:(id)arg1 highlightedImage:(id)arg2;
- (void)adaptFirstRightItemWithTitle:(id)arg1;
- (void)adaptLeftItemWithNormalImage:(id)arg1 highlightedImage:(id)arg2;
- (id)createHighlightedImageWithTitle:(id)arg1;
- (id)createNormalImageWithTitle:(id)arg1;
- (void)adaptLeftItemWithTitle:(id)arg1 backArrow:(_Bool)arg2;
- (void)updateSegmentControlWithIndex:(long long)arg1;
- (long long)getCurrentSelectedSegmentIndex;
- (void)adaptCenterItemWithView:(id)arg1;
- (void)updateSeparateLine;
- (void)updateSegmentControl;
- (void)updateNavBarWithTitle:(id)arg1;
- (void)adaptNavBarWithBgTag:(int)arg1 navTitle:(id)arg2 segmentArray:(id)arg3;
- (void)didReceiveMemoryWarning;
- (void)refreshNavBarFrame;
- (void)viewWillLayoutSubviews;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

