//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface BfdAgent : NSObject
{
    int reportPolicy;
    NSString *_gid;
    NSString *_sid;
    NSString *_appkey;
    NSString *_operator;
    double sidTimeout;
    double reportTimeout;
}

+ (id)recommendSearch:(id)arg1 bidlst:(id)arg2 options:(id)arg3;
+ (id)mobideaInit;
+ (void)appDidBecomeActive;
+ (void)appWillResignActive;
+ (id)mobideaSessionID;
+ (id)MDispatcher:(id)arg1 str1:(id)arg2 str2:(id)arg3 requests:(id)arg4 options:(id)arg5 ws:(int)arg6 timestamp:(id)arg7;
+ (id)MSession:(id)arg1 appversion:(id)arg2 options:(id)arg3;
+ (id)MUserInfo:(id)arg1 options:(id)arg2;
+ (id)addUser;
+ (id)onlineConfig;
+ (id)event:(id)arg1 options:(id)arg2;
+ (id)position:(id)arg1 latitude:(double)arg2 longitude:(double)arg3 options:(id)arg4;
+ (id)order:(id)arg1 lst:(id)arg2 orderId:(id)arg3 options:(id)arg4;
+ (id)rmCart:(id)arg1 itemId:(id)arg2 options:(id)arg3;
+ (id)addCart:(id)arg1 lst:(id)arg2 options:(id)arg3;
+ (id)feedback:(id)arg1 recommendId:(id)arg2 itemId:(id)arg3 options:(id)arg4;
+ (id)recommend:(id)arg1 recommendId:(id)arg2 options:(id)arg3;
+ (id)search:(id)arg1 queryString:(id)arg2 options:(id)arg3;
+ (id)visit:(id)arg1 itemId:(id)arg2 options:(id)arg3;
+ (id)endPageView:(id)arg1 pageName:(id)arg2 options:(id)arg3;
+ (id)beginPageView:(id)arg1 pageName:(id)arg2 options:(id)arg3;
+ (id)addUser:(id)arg1 userId:(id)arg2 options:(id)arg3;
+ (id)rmItem:(id)arg1 itemId:(id)arg2 options:(id)arg3;
+ (id)addItem:(id)arg1 itemId:(id)arg2 options:(id)arg3;
+ (id)pay:(id)arg1 orderId:(id)arg2 options:(id)arg3;
@property(nonatomic) int reportPolicy; // @synthesize reportPolicy;
@property(nonatomic) double reportTimeout; // @synthesize reportTimeout;
@property(nonatomic) double sidTimeout; // @synthesize sidTimeout;
@property(retain) NSString *operator; // @synthesize operator=_operator;
@property(retain) NSString *appkey; // @synthesize appkey=_appkey;
@property(retain) NSString *sid; // @synthesize sid=_sid;
@property(retain) NSString *gid; // @synthesize gid=_gid;
- (void).cxx_destruct;
- (_Bool)bfdAgentGetCfgs;
- (void)loadChache;
- (void)cache:(id)arg1;
- (void)watchStatus:(id)arg1;
- (void)startReport;
- (void)bfdAgentUpdateToken;
- (id)init;

@end

