//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseViewController.h"

#import "BaiduAdCellDelegate-Protocol.h"
#import "BookShelfCellDelegate-Protocol.h"
#import "CustomAdUtilsDelegate-Protocol.h"
#import "ReadingViewControllerDelegate-Protocol.h"
#import "ResourceWebViewDelegate-Protocol.h"
#import "SyncBookDelegate-Protocol.h"
#import "UIAlertViewDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class BookItem, BookShelfAdItem, DetailTextView, NSArray, NSDictionary, NSMutableArray, NSMutableDictionary, NSString, ResourceItem, UIButton, UIImageView, UILabel, UITableView, UITableViewCell, UIView;
@protocol BookShelfViewDelegate;

@interface BookShelvesViewController : BaseViewController <BookShelfCellDelegate, UIAlertViewDelegate, UITableViewDelegate, UITableViewDataSource, SyncBookDelegate, ReadingViewControllerDelegate, ResourceWebViewDelegate, CustomAdUtilsDelegate, BaiduAdCellDelegate>
{
    NSArray *bookDataArr;
    long long bookCount;
    UIButton *overView;
    UIButton *noBookView;
    NSMutableArray *editMenuRecordArr;
    BookItem *selectedBookItem;
    ResourceItem *selectedResourceItem;
    long long selectedChapterNum;
    long long selectedPageNum;
    NSMutableArray *selectedDirectoryArray;
    UIView *lastReadOverView;
    UITableViewCell *selectedLastReadCell;
    unsigned long long feedingBookCount;
    unsigned long long feededBookCount;
    NSArray *feedBookDataArr;
    _Bool forceShowAd;
    _Bool isDeleting;
    _Bool isHostAdAlive;
    NSDictionary *bookDownloadStatusDic;
    BookShelfAdItem *bookShelfTopAdItem;
    BookShelfAdItem *bookShelfBottomAdItem;
    _Bool isShowAd;
    _Bool isShowGDTAd;
    _Bool isShowBaiduAd;
    _Bool baiduFirstAdDisplayed;
    _Bool baiduFifthAdDisplayed;
    UIImageView *_backGroundImage;
    UITableView *_shelfTable;
    NSMutableDictionary *_bookDataDic;
    NSString *_updateStr;
    UILabel *_uploadText;
    DetailTextView *_totalBookNumber;
    id <BookShelfViewDelegate> _delegate;
}

@property(nonatomic) __weak id <BookShelfViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) DetailTextView *totalBookNumber; // @synthesize totalBookNumber=_totalBookNumber;
@property(retain, nonatomic) UILabel *uploadText; // @synthesize uploadText=_uploadText;
@property(retain, nonatomic) NSString *updateStr; // @synthesize updateStr=_updateStr;
@property(retain, nonatomic) NSMutableDictionary *bookDataDic; // @synthesize bookDataDic=_bookDataDic;
@property(retain, nonatomic) UITableView *shelfTable; // @synthesize shelfTable=_shelfTable;
@property(retain, nonatomic) UIImageView *backGroundImage; // @synthesize backGroundImage=_backGroundImage;
- (void).cxx_destruct;
- (void)customAdUtilsInmobiAdSucceedWithPositionTag:(int)arg1;
- (void)BACD_showDeleteCell:(id)arg1;
- (void)customAdUtilsBaiduAdClicked:(id)arg1;
- (void)customAdUtilsBaiduAdSucceedWithPositionTag:(int)arg1;
- (void)customAdUtilsGDTAdSucceed;
- (void)customAdUtilsGDTAdStarted:(id)arg1;
- (void)allSelfAdRequestFinished;
- (void)progressHideWithCancelBtn;
- (void)needChangeToOptimizeModeViewWithBookItem:(id)arg1 resourceName:(id)arg2;
- (void)needChangeToResourceWebViewWithBookItem:(id)arg1 resourceName:(id)arg2 chapterNum:(long long)arg3;
- (void)needChangeToNormalReadingViewWithBookItem:(id)arg1 chapterItem:(id)arg2 resourceName:(id)arg3 chapterNum:(long long)arg4;
- (void)removeDownloadObserver;
- (void)refreshCellWithStatus:(id)arg1;
- (void)addDownloadObserver;
- (void)syncBookFinished;
- (void)SB_needHideProgressWithMsg:(id)arg1;
- (void)SB_needShowProgress;
- (void)hideLastReadOverViewWithSuccess:(_Bool)arg1;
- (void)addLastReadOverView:(id)arg1;
- (void)goLastReadingViewWithCell:(id)arg1;
- (void)editMenuHided:(id)arg1;
- (void)editMenuDisplayed:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)goReadingView:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)deleteBook:(id)arg1;
- (void)stickBook:(id)arg1;
- (void)addPopAnimationToView:(id)arg1 withOverView:(id)arg2;
- (void)createFeedTipView;
- (long long)getFeedBookItemIndex;
- (_Bool)detectIfFeedBookItemExist;
- (void)feedBook:(id)arg1;
- (void)showDownloadOptionWithBookItem:(id)arg1;
- (void)downloadBook:(id)arg1;
- (void)normalCellInitialize:(id)arg1 withIndexPath:(id)arg2;
- (void)feedCellInitialize:(id)arg1 withIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)tableView:(id)arg1 titleForDeleteConfirmationButtonForRowAtIndexPath:(id)arg2;
- (_Bool)showBookshelfFifthAdWithAdItem:(id)arg1;
- (_Bool)showBookshelfFirstAdWithAdItem:(id)arg1;
- (void)sortBookShelfAdWithAdItemsArray:(id)arg1 bookArray:(id)arg2;
- (void)insertFeedBookItemWithOrignArr:(id)arg1 withAdItemsArr:(id)arg2;
- (void)filterFeedBookWithOriginArr:(id)arg1 withFeedArr:(id)arg2;
- (id)sortBookDataWithAdItemsArr:(id)arg1;
- (id)adItemsArr;
- (void)reloadShelfTable;
- (void)reloadBookData;
- (void)refreshShelfTable;
- (void)parseUpdatedData:(id)arg1;
- (void)startCheckUpdateRequest;
- (void)startADRequest;
- (void)removeTableHeaderView;
- (void)addTableHeaderViewWithData:(id)arg1;
- (void)startShelfMessageRequest;
- (void)createNoBookView;
- (void)onLongPress:(id)arg1;
- (void)checkUpdate;
- (void)triggerUpdate;
- (void)addShelfTableView;
- (void)appVersionFinished:(id)arg1;
- (void)startAppVersionRequest;
- (id)changeArrayToString:(id)arg1;
- (void)sendBookRenovateLog:(id)arg1 url:(id)arg2 bookIds:(id)arg3;
- (void)resendLocalBookRenovateLog;
- (void)addRenovateTagForOlderVersion;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

