//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseViewController.h"

#import "AvatarBtnViewDelegate-Protocol.h"
#import "CustomAdUtilsDelegate-Protocol.h"
#import "MBProgressHUDDelegate-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"
#import "UIAlertViewDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "UITextViewDelegate-Protocol.h"

@class AFHTTPRequestOperation, BookItem, BookShelfAdItem, EGOImageView, MBProgressHUD, MSLabel, NSMutableArray, NSString, NSTimer, UIButton, UIImageView, UILabel, UITableView, UIView;

@interface BookDetailViewController : BaseViewController <MBProgressHUDDelegate, UITextViewDelegate, UIActionSheetDelegate, UIAlertViewDelegate, UIGestureRecognizerDelegate, CustomAdUtilsDelegate, UITableViewDelegate, UITableViewDataSource, AvatarBtnViewDelegate>
{
    _Bool bookHadAdded;
    int currentDownloadTag;
    NSString *postStatusText;
    UITableView *detailTableView;
    UIView *bookInfoView;
    UIView *bookDetailView;
    UIView *bookDescriptionView;
    UIView *bookReviewView;
    UIView *topicEnterView;
    MBProgressHUD *progress;
    MSLabel *bookIntroduceText;
    _Bool introduceTextOutspreaded;
    UIImageView *arrowDownIamge;
    UIButton *readOnlineBtn;
    NSMutableArray *dataInfo;
    EGOImageView *bookImage;
    UIButton *addBookshelf;
    UIButton *haveAddBookshelfBtn;
    UILabel *bookName;
    UILabel *bookCategory;
    UIButton *authorNameBtn;
    UILabel *wordCount;
    UILabel *latestUpdate;
    UILabel *bookFollower;
    UILabel *bookFollowerRank;
    UILabel *bookSerializeSpeed;
    UILabel *bookRetentionRatio;
    UILabel *bookRetentionRatioRank;
    UILabel *bookScoreCountRatio;
    UILabel *bookScoreTotalCount;
    UILabel *bookCreater;
    AFHTTPRequestOperation *requestCanCancel;
    _Bool startListenning;
    NSTimer *listenningTimer;
    NSMutableArray *recommendBookListArray;
    UIView *recommendBookListView;
    UIView *bookDetailAdView;
    EGOImageView *adImageView;
    UILabel *adTitle;
    UIImageView *promotionImage;
    UILabel *adDesc;
    UIView *interestingBookListView;
    UIButton *moreBtn;
    UIView *interestingBookList;
    NSMutableArray *interestingBooks;
    BookShelfAdItem *currentAdItem;
    _Bool bookReviewRequestFinished;
    _Bool baiduAdViewDisplayed;
    _Bool _isModalStyle;
    BookItem *_bookItem;
}

@property(nonatomic) _Bool isModalStyle; // @synthesize isModalStyle=_isModalStyle;
@property(retain, nonatomic) BookItem *bookItem; // @synthesize bookItem=_bookItem;
- (void).cxx_destruct;
- (void)customAdUtilsInmobiAdSucceedWithPositionTag:(int)arg1;
- (void)customAdUtilsBaiduAdClicked:(id)arg1;
- (void)customAdUtilsBaiduAdSucceedWithPositionTag:(int)arg1;
- (void)customAdUtilsGDTAdSucceed;
- (void)customAdUtilsGDTAdStarted:(id)arg1;
- (void)avatarBtnClicked:(id)arg1;
- (void)listenDownloadingStatus;
- (void)changePreviewBtnStatusWithDownloading:(_Bool)arg1;
- (void)changePreviewBtnStatus;
- (void)previewAllBook;
- (void)shareBook;
- (void)onClickSecondRightItem;
- (void)onClickFirstRightItem;
- (void)onClickLeftItem;
- (void)hudWasHiddenByCancelBtn;
- (void)actionSheet:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)getUserItemByTopicDetailItem:(id)arg1;
- (void)goReadingView;
- (void)goBookDetailView:(id)arg1;
- (void)goMoreBooksView;
- (void)goNormalTopicListView;
- (void)goBookReviewDetailViewWithItem:(id)arg1;
- (void)goPublicTopicScoreView;
- (void)goReviewTopicListView;
- (void)goTagsBookListViewWithTitle:(id)arg1;
- (void)goAuthorBookListView;
- (void)setBlackLabelProperty:(id)arg1;
- (void)setGreyLabelProperty:(id)arg1;
- (void)setBlackTitleLabelProperty:(id)arg1;
- (void)onClickShowBookDetailList:(id)arg1;
- (void)createBookListViewWithItem:(id)arg1 idx:(unsigned long long)arg2;
- (void)updateRecommedBookListView;
- (void)jsonParser:(id)arg1;
- (void)startRecommendBookListRequest;
- (void)createRecommedBookListView;
- (void)updateInterestingBookListView;
- (void)requestInterestingBook;
- (void)createInterestingBookListView;
- (void)createTopicEnterView;
- (void)onClickShowAd:(id)arg1;
- (void)updateBookDetailAdView;
- (void)startADRequest;
- (void)createBookDetailAdView;
- (id)createRatingImage:(long long)arg1;
- (id)createBookReviewListViewWithItem:(id)arg1 positionY:(double)arg2 needSeparator:(_Bool)arg3;
- (void)updateBookReviewViewWithData:(id)arg1;
- (void)startBookReviewRequest;
- (void)createBookReviewView;
- (void)triggerBookDescriptionViewTapped;
- (void)resetBookIntroduceTextViewFrame;
- (void)createBookDescriptionView:(double)arg1;
- (id)createTagsView:(double)arg1;
- (id)createBookDataView;
- (void)createBookDetailView;
- (id)cutWordCount:(long long)arg1;
- (void)showHaveCancelAlert;
- (void)removeFollower;
- (void)cancelSubscribe;
- (void)showHaveAddAlert;
- (void)addFollower;
- (void)addToBookShelf;
- (void)createBookInfoView;
- (void)updateBookDetailData:(id)arg1;
- (void)startDetailDataRequest;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)resetAllViewsFrame;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

