//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BookItem.h"

@class NSString;

@interface BookShelfItem : BookItem
{
    _Bool _feeded;
    _Bool _isSelected;
    NSString *_haveUpdate;
    NSString *_haveStick;
    NSString *_chapterLink;
    NSString *_chapterTitle;
    NSString *_stickStr;
    NSString *_chapterNum;
    NSString *_pageNum;
    NSString *_lastUpdateTime;
    NSString *_lastVisitTime;
    NSString *_lastReadSourceId;
    NSString *_lastReadSourceName;
    unsigned long long _feededChapterCount;
    unsigned long long _topicCount;
    NSString *_customDesc;
}

@property(nonatomic) NSString *customDesc; // @synthesize customDesc=_customDesc;
@property(nonatomic) _Bool isSelected; // @synthesize isSelected=_isSelected;
@property(nonatomic) unsigned long long topicCount; // @synthesize topicCount=_topicCount;
@property(nonatomic) unsigned long long feededChapterCount; // @synthesize feededChapterCount=_feededChapterCount;
@property(nonatomic) _Bool feeded; // @synthesize feeded=_feeded;
@property(retain, nonatomic) NSString *lastReadSourceName; // @synthesize lastReadSourceName=_lastReadSourceName;
@property(retain, nonatomic) NSString *lastReadSourceId; // @synthesize lastReadSourceId=_lastReadSourceId;
@property(retain, nonatomic) NSString *lastVisitTime; // @synthesize lastVisitTime=_lastVisitTime;
@property(retain, nonatomic) NSString *lastUpdateTime; // @synthesize lastUpdateTime=_lastUpdateTime;
@property(retain, nonatomic) NSString *pageNum; // @synthesize pageNum=_pageNum;
@property(retain, nonatomic) NSString *chapterNum; // @synthesize chapterNum=_chapterNum;
@property(retain, nonatomic) NSString *stickStr; // @synthesize stickStr=_stickStr;
@property(retain, nonatomic) NSString *chapterTitle; // @synthesize chapterTitle=_chapterTitle;
@property(retain, nonatomic) NSString *chapterLink; // @synthesize chapterLink=_chapterLink;
@property(retain, nonatomic) NSString *haveStick; // @synthesize haveStick=_haveStick;
@property(retain, nonatomic) NSString *haveUpdate; // @synthesize haveUpdate=_haveUpdate;
- (void).cxx_destruct;

@end

