//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class BookListSearchItem, EGOImageView, UILabel;

@interface BookListSearchCell : UITableViewCell
{
    _Bool _fromBookListView;
    EGOImageView *_bookImage;
    UILabel *_bookName;
    UILabel *_bookIntroduce;
    BookListSearchItem *_info;
    UILabel *_alreadyAdded;
}

@property(nonatomic) _Bool fromBookListView; // @synthesize fromBookListView=_fromBookListView;
@property(retain, nonatomic) UILabel *alreadyAdded; // @synthesize alreadyAdded=_alreadyAdded;
@property(retain, nonatomic) BookListSearchItem *info; // @synthesize info=_info;
@property(retain, nonatomic) UILabel *bookIntroduce; // @synthesize bookIntroduce=_bookIntroduce;
@property(retain, nonatomic) UILabel *bookName; // @synthesize bookName=_bookName;
@property(retain, nonatomic) EGOImageView *bookImage; // @synthesize bookImage=_bookImage;
- (void).cxx_destruct;
- (void)setInfoValue;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

