//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface ChapterPreviewUtils : NSObject
{
}

+ (id)readResourceDataFromLocalFileWithBookId:(id)arg1;
+ (id)getPreviewedResourceItemsWithBookId:(id)arg1;
+ (id)getAllLocalResourceDataWithBookId:(id)arg1;
+ (id)getResourceFileNameWithBookId:(id)arg1;
+ (id)readFromLocalFileWithBookId:(id)arg1 resourceHost:(id)arg2 linkStr:(id)arg3;
+ (_Bool)writeToLocalFile:(id)arg1 withData:(id)arg2;
+ (_Bool)deletePreviewedChaptersWithBookId:(id)arg1 resourceHost:(id)arg2;
+ (_Bool)deletePreviewedAllChaptersWithBookId:(id)arg1;
+ (id)previewdDirectoryPathWithBookId:(id)arg1;
+ (id)previewdDirectoryPath;
+ (id)getPreviewedChaptersWithBookId:(id)arg1 resourceHost:(id)arg2;
+ (id)getPreviewedChapterDirectoryWithBookId:(id)arg1;
+ (_Bool)detectChapterHadPreviewedWithBookId:(id)arg1 resourceHost:(id)arg2 linkStr:(id)arg3;
+ (id)getFileNameWithBookId:(id)arg1 resourceHost:(id)arg2 linkStr:(id)arg3;

@end

