//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, NSString;

@interface CpChapterModel : NSObject
{
    NSMutableDictionary *chapterKeysDic;
    NSString *_bookId;
}

@property(retain, nonatomic) NSString *bookId; // @synthesize bookId=_bookId;
- (void).cxx_destruct;
- (id)decryptChapterContentIfNeededWithChapterItem:(id)arg1;
- (_Bool)detectKeyExistWithChapterId:(id)arg1;
- (id)getChapterKeyWithChapterId:(id)arg1;
- (void)updateChapterKeysDataWithKey:(id)arg1 chapterId:(id)arg2;
- (id)getLocalChapterKeys;
- (void)updateChapterKeysDicWithDic:(id)arg1;
- (id)init;

@end

