//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface CustomLink : NSObject
{
}

+ (void)alertWithTitle:(id)arg1;
+ (void)goBookListDetailViewWithID:(id)arg1 fromVC:(id)arg2;
+ (void)goBookDetailViewWithBookId:(id)arg1 fromVC:(id)arg2;
+ (void)goWebViewWithUrlStr:(id)arg1 fromVC:(id)arg2;
+ (void)goTopicDetailViewWithPostID:(id)arg1 postType:(id)arg2 fromVC:(id)arg3;
+ (void)triggerLinkWithLinkStr:(id)arg1 fromVC:(id)arg2;

@end

