//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface CustomRequestUtils : NSObject
{
}

+ (void)setCustomContentTypesWithResponseSerializer:(id)arg1;
+ (void)setCustomRquestHeaderWithRequest:(id)arg1;
+ (void)setCustomUserAgentToRequest:(id)arg1 withUrlStr:(id)arg2;
+ (void)createNewRequestWithMethod:(id)arg1 urlStr:(id)arg2 params:(id)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
+ (id)createNewPrePostRequest:(id)arg1 params:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
+ (id)getMimeTypeImageData:(id)arg1;
+ (void)createNewMultipartFormPostRequest:(id)arg1 normalParams:(id)arg2 dataParams:(id)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
+ (void)createNewPostRequest:(id)arg1 params:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
+ (id)createPreRequest:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
+ (id)createNewRequest:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
+ (id)createHTMLRequest:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;

@end

