//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "BaiduAdUtilsDelegate-Protocol.h"
#import "GDTAdUtilsDelegate-Protocol.h"
#import "InmobiAdUtilsDelegate-Protocol.h"

@class BookShelfAdItem, NSMutableArray, NSString, UIView;
@protocol CustomAdUtilsDelegate, CustomSplashAdUtilsDelegate;

@interface CustomAdUtils : NSObject <GDTAdUtilsDelegate, BaiduAdUtilsDelegate, InmobiAdUtilsDelegate>
{
    _Bool selfAdRequestFinished;
    _Bool _readingViewShowGDTAd;
    _Bool _bookShelfTopShowGDTAd;
    _Bool _bookShelfBottomShowGDTAd;
    _Bool _bookDetailViewShowGDTAd;
    _Bool _menuViewShowGDTAd;
    _Bool _splashViewShowGDTAd;
    _Bool _readingViewShowBaiduAd;
    _Bool _bookShelfTopShowBaiduAd;
    _Bool _bookShelfBottomShowBaiduAd;
    _Bool _bookDetailViewShowBaiduAd;
    _Bool _menuViewShowBaiduAd;
    _Bool _splashViewShowBaiduAd;
    _Bool _readingViewShowInmobiAd;
    _Bool _bookShelfTopShowInmobiAd;
    _Bool _bookShelfBottomShowInmobiAd;
    _Bool _bookDetailViewShowInmobiAd;
    _Bool _menuViewShowInmobiAd;
    _Bool _splashViewShowInmobiAd;
    _Bool _splashAdShowed;
    id <CustomAdUtilsDelegate> _customAdUtilsDelegate;
    id <CustomSplashAdUtilsDelegate> _customSplashAdUtilsDelegate;
    BookShelfAdItem *_lastReadingViewBookShelfAdItem;
    NSString *_bookShelfTopThirdParty;
    NSString *_bookShelfBottomThirdParty;
    NSString *_bookDetailThirdParty;
    NSString *_bookReadingThirdParty;
    NSString *_bookMenuThirdParty;
    NSString *_bookSplashThirdParty;
    NSMutableArray *_readingViewAdListArray;
    UIView *_containView;
}

+ (id)sharedAdUtils;
@property(retain, nonatomic) UIView *containView; // @synthesize containView=_containView;
@property(retain, nonatomic) NSMutableArray *readingViewAdListArray; // @synthesize readingViewAdListArray=_readingViewAdListArray;
@property(nonatomic) _Bool splashAdShowed; // @synthesize splashAdShowed=_splashAdShowed;
@property(retain, nonatomic) NSString *bookSplashThirdParty; // @synthesize bookSplashThirdParty=_bookSplashThirdParty;
@property(retain, nonatomic) NSString *bookMenuThirdParty; // @synthesize bookMenuThirdParty=_bookMenuThirdParty;
@property(retain, nonatomic) NSString *bookReadingThirdParty; // @synthesize bookReadingThirdParty=_bookReadingThirdParty;
@property(retain, nonatomic) NSString *bookDetailThirdParty; // @synthesize bookDetailThirdParty=_bookDetailThirdParty;
@property(retain, nonatomic) NSString *bookShelfBottomThirdParty; // @synthesize bookShelfBottomThirdParty=_bookShelfBottomThirdParty;
@property(retain, nonatomic) NSString *bookShelfTopThirdParty; // @synthesize bookShelfTopThirdParty=_bookShelfTopThirdParty;
@property(nonatomic) _Bool splashViewShowInmobiAd; // @synthesize splashViewShowInmobiAd=_splashViewShowInmobiAd;
@property(nonatomic) _Bool menuViewShowInmobiAd; // @synthesize menuViewShowInmobiAd=_menuViewShowInmobiAd;
@property(nonatomic) _Bool bookDetailViewShowInmobiAd; // @synthesize bookDetailViewShowInmobiAd=_bookDetailViewShowInmobiAd;
@property(nonatomic) _Bool bookShelfBottomShowInmobiAd; // @synthesize bookShelfBottomShowInmobiAd=_bookShelfBottomShowInmobiAd;
@property(nonatomic) _Bool bookShelfTopShowInmobiAd; // @synthesize bookShelfTopShowInmobiAd=_bookShelfTopShowInmobiAd;
@property(nonatomic) _Bool readingViewShowInmobiAd; // @synthesize readingViewShowInmobiAd=_readingViewShowInmobiAd;
@property(nonatomic) _Bool splashViewShowBaiduAd; // @synthesize splashViewShowBaiduAd=_splashViewShowBaiduAd;
@property(nonatomic) _Bool menuViewShowBaiduAd; // @synthesize menuViewShowBaiduAd=_menuViewShowBaiduAd;
@property(nonatomic) _Bool bookDetailViewShowBaiduAd; // @synthesize bookDetailViewShowBaiduAd=_bookDetailViewShowBaiduAd;
@property(nonatomic) _Bool bookShelfBottomShowBaiduAd; // @synthesize bookShelfBottomShowBaiduAd=_bookShelfBottomShowBaiduAd;
@property(nonatomic) _Bool bookShelfTopShowBaiduAd; // @synthesize bookShelfTopShowBaiduAd=_bookShelfTopShowBaiduAd;
@property(nonatomic) _Bool readingViewShowBaiduAd; // @synthesize readingViewShowBaiduAd=_readingViewShowBaiduAd;
@property(nonatomic) _Bool splashViewShowGDTAd; // @synthesize splashViewShowGDTAd=_splashViewShowGDTAd;
@property(nonatomic) _Bool menuViewShowGDTAd; // @synthesize menuViewShowGDTAd=_menuViewShowGDTAd;
@property(nonatomic) _Bool bookDetailViewShowGDTAd; // @synthesize bookDetailViewShowGDTAd=_bookDetailViewShowGDTAd;
@property(nonatomic) _Bool bookShelfBottomShowGDTAd; // @synthesize bookShelfBottomShowGDTAd=_bookShelfBottomShowGDTAd;
@property(nonatomic) _Bool bookShelfTopShowGDTAd; // @synthesize bookShelfTopShowGDTAd=_bookShelfTopShowGDTAd;
@property(nonatomic) _Bool readingViewShowGDTAd; // @synthesize readingViewShowGDTAd=_readingViewShowGDTAd;
@property(retain, nonatomic) BookShelfAdItem *lastReadingViewBookShelfAdItem; // @synthesize lastReadingViewBookShelfAdItem=_lastReadingViewBookShelfAdItem;
@property(nonatomic) __weak id <CustomSplashAdUtilsDelegate> customSplashAdUtilsDelegate; // @synthesize customSplashAdUtilsDelegate=_customSplashAdUtilsDelegate;
@property(nonatomic) __weak id <CustomAdUtilsDelegate> customAdUtilsDelegate; // @synthesize customAdUtilsDelegate=_customAdUtilsDelegate;
- (void).cxx_destruct;
- (void)IAUD_loadAdSucceedWithPositionTag:(int)arg1;
- (void)BAUD_splashAdClicked:(id)arg1;
- (void)BAUD_splashAdRequestSucceed:(id)arg1;
- (void)BAUD_nativeAdClicked:(id)arg1;
- (void)BAUD_nativeAdRequestSucceedWithAdPosition:(int)arg1;
- (_Bool)showInmobiAdByUmengRatio;
- (_Bool)showBaiduAdByUmengRatio;
- (_Bool)showGDTAdByUmengRatio;
- (void)deleteLocalAds;
- (void)gdtAdRequestSucceedWithPositionTag:(int)arg1;
- (void)gdtAdRequestStarted:(id)arg1 withPositionTag:(int)arg2;
- (void)requestInmobiAdWithPositionTag:(int)arg1;
- (void)requestSplashBaiduAd:(id)arg1;
- (void)requestBaiduAdWithPositionTag:(int)arg1;
- (void)requestGDTAdWithPositionTag:(int)arg1;
- (void)requestMenuViewAd:(CDUnknownBlockType)arg1 failedBlock:(CDUnknownBlockType)arg2;
- (void)requestReadingViewAd:(CDUnknownBlockType)arg1 failedBlock:(CDUnknownBlockType)arg2;
- (void)requestBookDetailViewAd:(CDUnknownBlockType)arg1 failedBlock:(CDUnknownBlockType)arg2;
- (void)updateBookShelfAdPositionStatus:(id)arg1;
- (void)requestBookShelvesAd:(CDUnknownBlockType)arg1 failedBlock:(CDUnknownBlockType)arg2;
- (void)requestSplashAd:(CDUnknownBlockType)arg1;
- (_Bool)isBookshelfBottomAdNotDeleted;
- (_Bool)isBookshelfTopAdNotDeleted;
- (_Bool)isBookshelfBottomAdEnabled;
- (_Bool)isBookshelfTopAdEnabled;
- (_Bool)allowShowMenuViewAd;
- (_Bool)allowShowReadingViewAd;
- (_Bool)allowShowBookDetailViewAd;
- (_Bool)allowShowInmobiBookShelfBottomAd;
- (_Bool)allowShowInmobiBookShelfTopAd;
- (_Bool)allowShowBaiduBookShelfBottomAd;
- (_Bool)allowShowBaiduBookShelfTopAd;
- (_Bool)allowShowGDTBookShelfBottomAd;
- (_Bool)allowShowGDTBookShelfTopAd;
- (_Bool)allowShowBookShelfBottomAd;
- (_Bool)allowShowBookShelfTopAd;
- (_Bool)allowShowBookShelvesAd;
- (_Bool)allowShowSplashAd;
- (_Bool)allowShowInmobiAd;
- (_Bool)allowShowBaiduAd;
- (_Bool)allowShowGDTAd;
- (id)selfAdWithPosition:(id)arg1;
- (void)removeLocalSelfAdWithPosition:(id)arg1;
- (void)setLocalSelfAdWithAds:(id)arg1 position:(id)arg2;
- (id)getLocalSelfAdWithPosition:(id)arg1;
- (void)parseAllSelfAdDic:(id)arg1;
- (void)startRequestAllSelfAd;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

