//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, UIView;
@protocol CutPageDelegate;

@interface CutPage : NSObject
{
    double viewWidth;
    double viewHeight;
    double labelWidth;
    double labelHeight;
    UIView *adView;
    _Bool _isScrollStyle;
    int _errorStatus;
    long long _autoReadingChapterNum;
    NSString *_bookId;
    id <CutPageDelegate> _delegate;
}

@property(nonatomic) __weak id <CutPageDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool isScrollStyle; // @synthesize isScrollStyle=_isScrollStyle;
@property(retain, nonatomic) NSString *bookId; // @synthesize bookId=_bookId;
@property(nonatomic) long long autoReadingChapterNum; // @synthesize autoReadingChapterNum=_autoReadingChapterNum;
@property(nonatomic) int errorStatus; // @synthesize errorStatus=_errorStatus;
- (void).cxx_destruct;
- (void)onClickShowAd:(id)arg1;
- (void)onClickRemitAd;
- (id)createBottomAdShadowView:(struct CGRect)arg1;
- (id)createBottomAdViewWithChapterNum:(long long)arg1 pageNum:(long long)arg2 chapterPageCount:(long long)arg3;
- (_Bool)allowShowWechatAdView:(double)arg1;
- (_Bool)allowShowBottomAdView:(double)arg1;
- (void)updateBottomView:(id)arg1 withPageCount:(unsigned long long)arg2 pageNum:(unsigned long long)arg3;
- (id)createBottomViewWithPageCount:(unsigned long long)arg1 pageNum:(unsigned long long)arg2;
- (void)updateHeaderView:(id)arg1 withChapterName:(id)arg2;
- (id)createHeaderViewWithChapterName:(id)arg1;
- (id)contentFont;
- (id)attrStrWithString:(id)arg1 color:(id)arg2 fontSize:(double)arg3;
- (void)openWeChat;
- (id)createWechatAD;
- (id)readedFirstChapterInBookID;
- (id)lastChapterNumInBookID;
- (id)wechatAdPositionInBookID;
- (id)wechatAdShowedInBookID;
- (id)createContentViewWithPageItem:(id)arg1 pageNum:(unsigned long long)arg2 needAd:(_Bool)arg3;
- (id)getPageView:(id)arg1 chapterName:(id)arg2 pageNum:(unsigned long long)arg3 needAd:(_Bool)arg4;
- (id)cutPageContent:(id)arg1;
- (void)setupSize:(struct CGSize)arg1;
- (void)dealloc;
- (id)init;

@end

