//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class CALayer, NSString, SvGifView, UIImageView, UILabel;
@protocol EGORefreshTableHeaderDelegate;

@interface EGORefreshTableHeaderView : UIView
{
    id _delegate;
    int _state;
    UILabel *_lastUpdatedLabel;
    UILabel *_statusLabel;
    CALayer *_arrowImage;
    SvGifView *_activityView;
    UIImageView *refreshFinishImage;
    NSString *isFrom;
}

@property(retain, nonatomic) NSString *isFrom; // @synthesize isFrom;
@property(nonatomic) id <EGORefreshTableHeaderDelegate> delegate; // @synthesize delegate=_delegate;
- (void)dealloc;
- (void)egoRefreshScrollViewDataSourceStartManualLoading:(id)arg1;
- (void)resetScrollViewPosition:(id)arg1;
- (void)egoRefreshScrollViewDataSourceDidFinishedLoading:(id)arg1;
- (void)egoRefreshScrollViewDidEndDragging:(id)arg1;
- (void)egoRefreshScrollViewDidScroll:(id)arg1;
- (void)resetArrowImageDirection;
- (void)setState:(int)arg1;
- (void)refreshLastUpdatedDate;
- (id)initWithFrame:(struct CGRect)arg1;

@end

