//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseViewController.h"

#import "ShareSDKViewDelegate-Protocol.h"
#import "UIWebViewDelegate-Protocol.h"

@class NSString, UIActivityIndicatorView, UIBarButtonItem, UIToolbar, UIWebView;

@interface EventViewController : BaseViewController <UIWebViewDelegate, ShareSDKViewDelegate>
{
    UIWebView *webView;
    UIActivityIndicatorView *activityIndicator;
    UIBarButtonItem *backBarButtonItem;
    UIBarButtonItem *forwardBarButtonItem;
    UIBarButtonItem *refreshBarButtonItem;
    UIToolbar *toolBar;
    unsigned long long currentShareType;
    NSString *callbackFuncName;
    _Bool _hideBottomToolbar;
    NSString *_eventTitle;
    NSString *_urlStr;
}

@property(nonatomic) _Bool hideBottomToolbar; // @synthesize hideBottomToolbar=_hideBottomToolbar;
@property(retain, nonatomic) NSString *urlStr; // @synthesize urlStr=_urlStr;
@property(retain, nonatomic) NSString *eventTitle; // @synthesize eventTitle=_eventTitle;
- (void).cxx_destruct;
- (void)onClickFirstRightItem;
- (void)shareMessageSucceed;
- (void)shareWithQQZone:(id)arg1;
- (void)shareWithWeixin:(id)arg1;
- (void)shareWithWeibo:(id)arg1;
- (id)parseQueryStr:(id)arg1;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)webViewDidStartLoad:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)goBack;
- (void)reloadClicked;
- (void)goForwardClicked;
- (void)goBackClicked;
- (void)loadWebPageWithString:(id)arg1;
- (void)updateToolbarItems;
- (void)addBottomToolbar;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

