//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface GameCenterItem : NSObject
{
    _Bool _pictureIsHorizontal;
    NSString *_gameId;
    NSString *_icon;
    NSString *_intro;
    NSString *_longIntro;
    long long _downloadCount;
    NSString *_link;
    NSString *_name;
    NSString *_size;
    long long _expValue;
    NSArray *_screenShotsArr;
    NSString *_created;
}

@property(retain, nonatomic) NSString *created; // @synthesize created=_created;
@property(retain, nonatomic) NSArray *screenShotsArr; // @synthesize screenShotsArr=_screenShotsArr;
@property(nonatomic) long long expValue; // @synthesize expValue=_expValue;
@property(retain, nonatomic) NSString *size; // @synthesize size=_size;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *link; // @synthesize link=_link;
@property(nonatomic) _Bool pictureIsHorizontal; // @synthesize pictureIsHorizontal=_pictureIsHorizontal;
@property(nonatomic) long long downloadCount; // @synthesize downloadCount=_downloadCount;
@property(retain, nonatomic) NSString *longIntro; // @synthesize longIntro=_longIntro;
@property(retain, nonatomic) NSString *intro; // @synthesize intro=_intro;
@property(retain, nonatomic) NSString *icon; // @synthesize icon=_icon;
@property(retain, nonatomic) NSString *gameId; // @synthesize gameId=_gameId;
- (void).cxx_destruct;
- (void)setValue:(id)arg1 forUndefinedKey:(id)arg2;
- (id)initWithDictionary:(id)arg1;

@end

