//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "GDTAppLinkServiceDelegate-Protocol.h"
#import "GDTWebViewControllerDelegate-Protocol.h"
#import "SKStoreProductViewControllerDelegate-Protocol.h"
#import "UIAlertViewDelegate-Protocol.h"

@class GDTAppLinkService, NSError, NSString, UIActivityIndicatorView, UIViewController;
@protocol GDTClickControllerDelegate;

@interface GDTClickController : NSObject <UIAlertViewDelegate, SKStoreProductViewControllerDelegate, GDTWebViewControllerDelegate, GDTAppLinkServiceDelegate>
{
    UIViewController *_currentViewController;
    GDTAppLinkService *_appLinkService;
    UIActivityIndicatorView *_loadingView;
    _Bool storePresented;
    NSString *_clickUrl;
    int _clickActionType;
    int _loadingTimeout;
    _Bool _innerBrowser;
    NSString *_itunesId;
    NSString *_adid;
    NSString *_campaignId;
    int openInAppStoreState;
    long long openInAppStoreStartTime;
    long long openInAppStorePresentCompleteTime;
    long long openInAppStoreLoadProductCompleteTime;
    long long openInAppStoreFinishTime;
    NSError *openInAppStoreError;
    id <GDTClickControllerDelegate> _stateListener;
}

+ (id)generateGDTUrlScheme:(id)arg1 clickId:(id)arg2 adId:(id)arg3;
+ (_Bool)canOpenUrlScheme:(id)arg1;
@property(nonatomic) id <GDTClickControllerDelegate> stateListener; // @synthesize stateListener=_stateListener;
- (void).cxx_destruct;
- (void)notifyListenerLeaveApp;
- (void)notifyListenerModalDidDismiss;
- (void)notifyListenerModalWillDismiss;
- (void)notifyListenerModalDidPresent;
- (void)notifyListenerModalWillPresent;
- (void)popUpWebViewDidClosed;
- (void)popUpWebViewWillClosed;
- (void)parseSuccessWithAppLinkHeader:(id)arg1;
- (void)parseFailure:(id)arg1;
- (void)reportAndOpenUrlScheme:(id)arg1 urlScheme:(id)arg2 adid:(id)arg3 acttype:(int)arg4;
- (void)openLandingPage:(id)arg1 clickActionType:(int)arg2 innerBrowser:(_Bool)arg3 itunesId:(id)arg4 campaignId:(id)arg5;
- (void)handleClick:(id)arg1;
- (void)openUrlScheme:(id)arg1;
- (void)openInnerBrowser:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)removeLoadingView;
- (void)openInAppStore:(id)arg1 clickUrl:(id)arg2 campaignId:(id)arg3;
- (void)productViewControllerDidFinish:(id)arg1;
- (id)initWithCurrentViewController:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

