//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface GlobalUtils : NSObject
{
}

+ (id)currentUserAgent;
+ (id)currentDeviceIp;
+ (id)currentAppType;
+ (void)uploadCaculateEventWithId:(id)arg1 attributes:(id)arg2;
+ (void)uploadCountEventWithId:(id)arg1 label:(id)arg2;
+ (id)getTagColorWithIndex:(long long)arg1;
+ (_Bool)isNewUser;
+ (void)setNewUserTag;
+ (id)getDeviceID;
+ (_Bool)versionLimitEnabled;
+ (void)updateVersionLimitWithValue:(id)arg1;
+ (void)logScreenSizeWithView:(id)arg1;
+ (_Bool)isValidateEmail:(id)arg1;
+ (id)encryptedPassword:(id)arg1;
+ (void)updateQuickLoginWithStatus:(_Bool)arg1;
+ (_Bool)allowShowQuickLogin;
+ (void)updateComicIslandWithStatus:(_Bool)arg1;
+ (_Bool)allowShowComicIsland;
+ (void)updateGameCenterWithStatus:(_Bool)arg1;
+ (_Bool)allowShowGameCenter;
+ (void)addSkipBackupAttributeToItemAtPath:(id)arg1;
+ (long long)getCurrentRealInterfaceOrientationWithVC:(id)arg1;
+ (id)translateStr:(id)arg1;
+ (void)setLabelLinkAtrributeWithLabel:(id)arg1;
+ (id)getMatchedDicFromOfficalLinkWithStr:(id)arg1 matchLength:(unsigned long long)arg2;
+ (void)replaceTitleToLinkWithLabel:(id)arg1 isOffical:(_Bool)arg2;
+ (id)pickBookNameFromUrl:(id)arg1;
+ (void)removeNotificationBadge;
+ (void)resetRemoteNotification;
+ (id)getAllPropertyNames:(Class)arg1;
+ (_Bool)isTimedOutError:(long long)arg1;
+ (_Bool)isNetworkError:(long long)arg1;
+ (id)getParentVC:(id)arg1;
+ (void)hideProgress:(id *)arg1 withMsg:(id)arg2;
+ (void)hideAndSetNil:(id *)arg1;
+ (id)snapshotWithVC:(id)arg1;
+ (void)customPresentViewControllerWithVC:(id)arg1 destinationVC:(id)arg2;
+ (void)customPushViewControllerWithVC:(id)arg1 destinationVC:(id)arg2;
+ (id)getCurrentNet;
+ (void)addUserExpRequestByRateApp;
+ (void)customOpenUrl:(id)arg1;
+ (void)updateUserInfoStatus:(_Bool)arg1;
+ (_Bool)getUserInfoStatus;
+ (id)updateRefreshTime:(id)arg1;
+ (void)refreshSecondaryNavBtn:(id)arg1;
+ (id)createSecondaryNavBtn:(struct CGRect)arg1 withTitle:(id)arg2;
+ (id)createHomePageNavigationBarWithRedColor:(id)arg1 withWidth:(double)arg2;

@end

