//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SKPaymentTransactionObserver-Protocol.h"
#import "SKProductsRequestDelegate-Protocol.h"

@class NSArray, NSMutableSet, NSSet, NSString, SKProductsRequest;
@protocol IAPHelperDelegate;

@interface IAPHelper : NSObject <SKProductsRequestDelegate, SKPaymentTransactionObserver>
{
    NSArray *skProducts;
    SKProductsRequest *_productsRequest;
    CDUnknownBlockType _completionHandler;
    NSSet *_productIdentifiers;
    NSMutableSet *_purchasedProductIdentifiers;
    id <IAPHelperDelegate> _delegate;
}

@property(nonatomic) __weak id <IAPHelperDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)provideContentForProductIdentifier:(id)arg1;
- (void)failedTransaction:(id)arg1;
- (void)restoreTransaction:(id)arg1;
- (void)showRetryAlert:(id)arg1 productId:(id)arg2;
- (void)startSynschronizeAcoount:(id)arg1 withProductId:(id)arg2;
- (void)completeTransaction:(id)arg1;
- (void)paymentQueue:(id)arg1 updatedTransactions:(id)arg2;
- (void)requestDidFinish:(id)arg1;
- (void)request:(id)arg1 didFailWithError:(id)arg2;
- (void)productsRequest:(id)arg1 didReceiveResponse:(id)arg2;
- (void)restoreCompletedTransactions;
- (void)buyProduct:(id)arg1;
- (_Bool)productPurchased:(id)arg1;
- (void)requestProductsWithCompletionHandler:(CDUnknownBlockType)arg1;
- (id)initWithProductIdentifiers:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

