//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "IMAdStoreDelegate-Protocol.h"
#import "IMConfigDelegate-Protocol.h"
#import "IMRenderViewDelegate-Protocol.h"
#import "IMTimerDelegate-Protocol.h"

@class IMAdStore, IMAdsConfig, IMRenderView, IMTimerManager, NSDictionary, NSString;
@protocol IMAdUnitDelegate;

@interface IMAdUnit : NSObject <IMAdStoreDelegate, IMRenderViewDelegate, IMConfigDelegate, IMTimerDelegate>
{
    _Bool _preloadedAdUnit;
    int _displayedScreens;
    int _placementType;
    long long _placementId;
    NSDictionary *_extras;
    NSString *_keywords;
    double _insertionTS;
    IMTimerManager *_timer;
    long long _currentState;
    NSDictionary *_adContent;
    NSString *_pubContent;
    IMAdsConfig *_config;
    id <IMAdUnitDelegate> _delegate;
    IMRenderView *_renderView;
    NSString *_impId;
    NSString *_adType;
    double _renderStartTS;
    IMAdStore *_store;
    struct CGRect _frame;
}

@property(retain, nonatomic) IMAdStore *store; // @synthesize store=_store;
@property(nonatomic) double renderStartTS; // @synthesize renderStartTS=_renderStartTS;
@property(retain, nonatomic) NSString *adType; // @synthesize adType=_adType;
@property(retain, nonatomic) NSString *impId; // @synthesize impId=_impId;
@property(nonatomic) struct CGRect frame; // @synthesize frame=_frame;
@property(nonatomic) int placementType; // @synthesize placementType=_placementType;
@property(nonatomic) int displayedScreens; // @synthesize displayedScreens=_displayedScreens;
@property(retain, nonatomic) IMRenderView *renderView; // @synthesize renderView=_renderView;
@property(nonatomic) __weak id <IMAdUnitDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) IMAdsConfig *config; // @synthesize config=_config;
@property(retain, nonatomic) NSString *pubContent; // @synthesize pubContent=_pubContent;
@property(retain, nonatomic) NSDictionary *adContent; // @synthesize adContent=_adContent;
@property long long currentState; // @synthesize currentState=_currentState;
@property(retain, nonatomic) IMTimerManager *timer; // @synthesize timer=_timer;
@property(nonatomic) _Bool preloadedAdUnit; // @synthesize preloadedAdUnit=_preloadedAdUnit;
@property(readonly, nonatomic) double insertionTS; // @synthesize insertionTS=_insertionTS;
@property(retain, nonatomic) NSString *keywords; // @synthesize keywords=_keywords;
@property(retain, nonatomic) NSDictionary *extras; // @synthesize extras=_extras;
@property(nonatomic) long long placementId; // @synthesize placementId=_placementId;
- (void).cxx_destruct;
- (void)dealloc;
- (void)submitEventForLoadFailedOnEarlyRefresh;
- (void)configUpdated:(id)arg1;
- (void)deinit;
- (void)timerHitForManager:(id)arg1;
- (void)adStore:(id)arg1 failedToLoadAdWithErrorCode:(int)arg2 andDescription:(id)arg3;
- (void)adStore:(id)arg1 didLoadAdWithResponse:(id)arg2 impId:(id)arg3 insertionTS:(id)arg4;
- (_Bool)parseAdResponse:(id)arg1;
- (id)createAdStoreRequest;
- (void)load;
- (id)init;
- (id)initWithPlacementId:(long long)arg1 adType:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

