//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IMAdUnit.h"

#import "IMRenderViewDelegate-Protocol.h"

@class NSString;

@interface IMAdUnit (Protected) <IMRenderViewDelegate>
- (void)imRenderViewFireAdFailed:(id)arg1;
- (void)imRenderViewFireAdReady:(id)arg1;
- (void)imRenderViewIncentActionComplete:(id)arg1;
- (void)imRenderViewDidInteractWithParams:(id)arg1 onRenderView:(id)arg2;
- (void)imRenderViewAdWillLeaveApplication:(id)arg1;
- (void)imRenderViewDidDismissScreen:(id)arg1;
- (void)imRenderViewWillDismissScreeen:(id)arg1;
- (void)imRenderViewWillPresentScreen:(id)arg1;
- (void)imRenderViewDidPresentScreen:(id)arg1;
- (void)imRenderView:(id)arg1 failedToLoad:(id)arg2;
- (void)imRenderViewFinishedLoading:(id)arg1;
- (void)imRenderViewAppearOnScreen:(id)arg1;
- (void)adAttached;
- (void)adDestroyed;
- (void)adActive;
- (void)adRendered;
- (void)adReady;
- (void)adLoaded;
- (void)adFailed;
- (void)adAvailable;
- (void)loading;
- (void)created;
- (void)sendCallBackForAdLoadFailure:(int)arg1 description:(id)arg2 extras:(id)arg3;
- (void)reportEvent:(id)arg1;
- (void)sendRenderTimeOutError;
- (_Bool)extractAdContent:(id)arg1;
- (void)loadRenderViewWithFrame:(struct CGRect)arg1 content:(id)arg2 placementType:(int)arg3;
- (id)getRenderContent;
- (id)getAdReqParams;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

