//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class IMNetworkServiceProvider;
@protocol IMImageCacheDelegate;

@interface IMImageFetchProperties : NSObject
{
    IMNetworkServiceProvider *_nsp;
    id <IMImageCacheDelegate> _delegate;
}

@property(nonatomic) __weak id <IMImageCacheDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) IMNetworkServiceProvider *nsp; // @synthesize nsp=_nsp;
- (void).cxx_destruct;

@end

