//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class IMImageCache, NSData, NSError, NSString;

@protocol IMImageCacheDelegate <NSObject>
- (void)imageCache:(IMImageCache *)arg1 failedToFetchImageForUrl:(NSString *)arg2 withError:(NSError *)arg3;
- (void)imageCache:(IMImageCache *)arg1 fetchedImageData:(NSData *)arg2 forUrl:(NSString *)arg3;
- (void)imageCache:(IMImageCache *)arg1 returnedImageDataFromCache:(NSData *)arg2 forUrl:(NSString *)arg3;
@end

