//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IMAsset.h"

#import "IMImageCacheDelegate-Protocol.h"
#import "IMStrandsViewPoolDelegate-Protocol.h"

@class NSData, NSString;

@interface IMImageAsset : IMAsset <IMImageCacheDelegate, IMStrandsViewPoolDelegate>
{
    NSString *_imageUrl;
    NSData *_imageData;
    double _startImageFetchTS;
}

@property(nonatomic) double startImageFetchTS; // @synthesize startImageFetchTS=_startImageFetchTS;
@property(retain, nonatomic) NSData *imageData; // @synthesize imageData=_imageData;
@property(retain, nonatomic) NSString *imageUrl; // @synthesize imageUrl=_imageUrl;
- (void).cxx_destruct;
- (void)imStrandsViewPoolResetView:(id)arg1 withProperties:(id)arg2;
- (void)imStrandsViewPoolCleanView:(id)arg1;
- (id)imStrandsViewPoolCreateViewWithProperties:(id)arg1;
- (void)dealloc;
- (void)imageCache:(id)arg1 failedToFetchImageForUrl:(id)arg2 withError:(id)arg3;
- (void)imageCache:(id)arg1 returnedImageDataFromCache:(id)arg2 forUrl:(id)arg3;
- (void)imageCache:(id)arg1 fetchedImageData:(id)arg2 forUrl:(id)arg3;
- (void)populateImageData:(id)arg1;
- (void)addImageToViewWithTransition:(_Bool)arg1;
- (void)fetchAssetResources;
- (_Bool)isStyleValid;
- (void)recycleView;
- (id)buildAssetView;
- (id)initWithJson:(id)arg1 withStyles:(id)arg2 atJPath:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

