//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData, NSMutableSet, NSString;

@interface IMImageData : NSObject
{
    NSData *_imageData;
    NSMutableSet *_tokens;
    NSString *_fileURL;
    long long _state;
}

@property(nonatomic) long long state; // @synthesize state=_state;
@property(retain, nonatomic) NSString *fileURL; // @synthesize fileURL=_fileURL;
@property(retain, nonatomic) NSMutableSet *tokens; // @synthesize tokens=_tokens;
@property(retain, nonatomic) NSData *imageData; // @synthesize imageData=_imageData;
- (void).cxx_destruct;
- (id)init;

@end

