//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "IMNetworkDelegate-Protocol.h"

@class NSMutableDictionary, NSString;

@interface IMImageCache : NSObject <IMNetworkDelegate>
{
    NSMutableDictionary *_delegates;
    NSMutableDictionary *_cache;
}

+ (id)sharedImageCache;
@property(retain, nonatomic) NSMutableDictionary *cache; // @synthesize cache=_cache;
@property(retain, nonatomic) NSMutableDictionary *delegates; // @synthesize delegates=_delegates;
- (void).cxx_destruct;
- (void)deleteImageForUrl:(id)arg1 withToken:(id)arg2;
- (void)networkServiceProvider:(id)arg1 request:(id)arg2 didGetResponse:(id)arg3;
- (void)fetchImageForUrl:(id)arg1 withDelegate:(id)arg2 withToken:(id)arg3;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

