//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "IMStrandDataSourceManagerDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class IMStrandDataSourceManager, NSDictionary, NSString, UITableView;
@protocol IMStrandTableViewAdapterDelegate, UITableViewDataSource, UITableViewDelegate;

@interface IMStrandTableViewAdapter : NSObject <UITableViewDataSource, UITableViewDelegate, IMStrandDataSourceManagerDelegate>
{
    _Bool _didRegisterNibOrClassForCells;
    _Bool _tableViewObserverFlag;
    id <IMStrandTableViewAdapterDelegate> _delegate;
    NSString *_keywords;
    NSDictionary *_extras;
    UITableView *_tableView;
    id <UITableViewDataSource> _originalDataSource;
    id <UITableViewDelegate> _originalDelegate;
    Class _tableViewCellClass;
    long long _placementID;
    IMStrandDataSourceManager *_dataSourceManager;
}

+ (id)adapterWithTableView:(id)arg1 placementId:(long long)arg2 adPositioning:(id)arg3 tableViewCellClass:(Class)arg4;
@property(retain, nonatomic) IMStrandDataSourceManager *dataSourceManager; // @synthesize dataSourceManager=_dataSourceManager;
@property(nonatomic) _Bool tableViewObserverFlag; // @synthesize tableViewObserverFlag=_tableViewObserverFlag;
@property(nonatomic) _Bool didRegisterNibOrClassForCells; // @synthesize didRegisterNibOrClassForCells=_didRegisterNibOrClassForCells;
@property(nonatomic) long long placementID; // @synthesize placementID=_placementID;
@property(nonatomic) Class tableViewCellClass; // @synthesize tableViewCellClass=_tableViewCellClass;
@property(nonatomic) __weak id <UITableViewDelegate> originalDelegate; // @synthesize originalDelegate=_originalDelegate;
@property(nonatomic) __weak id <UITableViewDataSource> originalDataSource; // @synthesize originalDataSource=_originalDataSource;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) NSDictionary *extras; // @synthesize extras=_extras;
@property(retain, nonatomic) NSString *keywords; // @synthesize keywords=_keywords;
@property(nonatomic) __weak id <IMStrandTableViewAdapterDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 moveRowAtIndexPath:(id)arg2 toIndexPath:(id)arg3;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (_Bool)tableView:(id)arg1 canMoveRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)tableView:(id)arg1 performAction:(SEL)arg2 forRowAtIndexPath:(id)arg3 withSender:(id)arg4;
- (_Bool)tableView:(id)arg1 canPerformAction:(SEL)arg2 forRowAtIndexPath:(id)arg3 withSender:(id)arg4;
- (_Bool)tableView:(id)arg1 shouldShowMenuForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 indentationLevelForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didEndEditingRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willBeginEditingRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 shouldIndentWhileEditingRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForDeleteConfirmationButtonForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didDeselectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willDeselectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didUnhighlightRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didHighlightRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 shouldHighlightRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 accessoryButtonTappedForRowWithIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didEndDisplayingCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)manager:(id)arg1 userWillLeaveApplicationFromAdAtIndexPath:(id)arg2;
- (void)manager:(id)arg1 adAtIndexPathDidDismissScreen:(id)arg2;
- (void)manager:(id)arg1 adAtIndexPathWillDismissScreen:(id)arg2;
- (void)manager:(id)arg1 adAtIndexPathDidPresentScreen:(id)arg2;
- (void)manager:(id)arg1 adAtIndexPathWillPresentScreen:(id)arg2;
- (void)manager:(id)arg1 adDidFailToLoadAtIndexPath:(id)arg2 withError:(id)arg3;
- (void)manager:(id)arg1 didRemoveAdsAtIndexPaths:(id)arg2;
- (void)manager:(id)arg1 didLoadAdAtIndexPath:(id)arg2;
- (id)visibleIndexPaths:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)registerNibOrClassIfNecessary;
- (void)dealloc;
- (id)initWithTableView:(id)arg1 placementId:(long long)arg2 adPositioning:(id)arg3 tableViewCellClass:(Class)arg4;
- (void)clearAds;
- (void)updateVisibleCells;
- (void)load;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

