//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSMutableOrderedSet;

@interface IMStrandPosition : NSObject <NSCopying>
{
    NSMutableOrderedSet *_fixedPositions;
    unsigned long long _stride;
}

+ (id)positioning;
@property(nonatomic) unsigned long long stride; // @synthesize stride=_stride;
@property(retain, nonatomic) NSMutableOrderedSet *fixedPositions; // @synthesize fixedPositions=_fixedPositions;
- (void).cxx_destruct;
- (void)enableRepeatingPositionsWithStride:(unsigned long long)arg1;
- (void)addFixedIndexPath:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;

@end

