//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class IMRequestStatus, IMStrandDataSourceManager, NSArray, NSIndexPath;

@protocol IMStrandDataSourceManagerDelegate <NSObject>

@optional
- (void)manager:(IMStrandDataSourceManager *)arg1 userWillLeaveApplicationFromAdAtIndexPath:(NSIndexPath *)arg2;
- (void)manager:(IMStrandDataSourceManager *)arg1 adAtIndexPathDidDismissScreen:(NSIndexPath *)arg2;
- (void)manager:(IMStrandDataSourceManager *)arg1 adAtIndexPathWillDismissScreen:(NSIndexPath *)arg2;
- (void)manager:(IMStrandDataSourceManager *)arg1 adAtIndexPathDidPresentScreen:(NSIndexPath *)arg2;
- (void)manager:(IMStrandDataSourceManager *)arg1 adAtIndexPathWillPresentScreen:(NSIndexPath *)arg2;
- (void)manager:(IMStrandDataSourceManager *)arg1 adDidFailToLoadAtIndexPath:(NSIndexPath *)arg2 withError:(IMRequestStatus *)arg3;
- (void)manager:(IMStrandDataSourceManager *)arg1 didRemoveAdsAtIndexPaths:(NSArray *)arg2;
- (void)manager:(IMStrandDataSourceManager *)arg1 didLoadAdAtIndexPath:(NSIndexPath *)arg2;
@end

