//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "IMStrandDataSourceManagerDelegate-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"

@class IMStrandDataSourceManager, NSDictionary, NSString, NSTimer, UICollectionView;
@protocol IMStrandCollectionViewAdadpterDelegate, UICollectionViewDataSource, UICollectionViewDelegate;

@interface IMStrandCollectionViewAdapter : NSObject <UICollectionViewDataSource, UICollectionViewDelegate, IMStrandDataSourceManagerDelegate>
{
    _Bool _didRegisterNibOrClassForCells;
    id <IMStrandCollectionViewAdadpterDelegate> _delegate;
    NSString *_keywords;
    NSDictionary *_extras;
    UICollectionView *_collectionView;
    id <UICollectionViewDataSource> _originalDataSource;
    id <UICollectionViewDelegate> _originalDelegate;
    Class _collectionViewCellClass;
    long long _placementID;
    NSTimer *_insertionTimer;
    IMStrandDataSourceManager *_dataSourceManager;
}

+ (id)adapterWithCollectionView:(id)arg1 placementId:(long long)arg2 adPositioning:(id)arg3 collectionViewCellClass:(Class)arg4;
@property(retain, nonatomic) IMStrandDataSourceManager *dataSourceManager; // @synthesize dataSourceManager=_dataSourceManager;
@property(retain, nonatomic) NSTimer *insertionTimer; // @synthesize insertionTimer=_insertionTimer;
@property(nonatomic) _Bool didRegisterNibOrClassForCells; // @synthesize didRegisterNibOrClassForCells=_didRegisterNibOrClassForCells;
@property(nonatomic) long long placementID; // @synthesize placementID=_placementID;
@property(nonatomic) Class collectionViewCellClass; // @synthesize collectionViewCellClass=_collectionViewCellClass;
@property(nonatomic) __weak id <UICollectionViewDelegate> originalDelegate; // @synthesize originalDelegate=_originalDelegate;
@property(nonatomic) __weak id <UICollectionViewDataSource> originalDataSource; // @synthesize originalDataSource=_originalDataSource;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(retain, nonatomic) NSDictionary *extras; // @synthesize extras=_extras;
@property(retain, nonatomic) NSString *keywords; // @synthesize keywords=_keywords;
@property(nonatomic) __weak id <IMStrandCollectionViewAdadpterDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (_Bool)collectionView:(id)arg1 shouldShowMenuForItemAtIndexPath:(id)arg2;
- (_Bool)collectionView:(id)arg1 shouldSelectItemAtIndexPath:(id)arg2;
- (_Bool)collectionView:(id)arg1 shouldHighlightItemAtIndexPath:(id)arg2;
- (_Bool)collectionView:(id)arg1 shouldDeselectItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 performAction:(SEL)arg2 forItemAtIndexPath:(id)arg3 withSender:(id)arg4;
- (void)collectionView:(id)arg1 didUnhighlightItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didHighlightItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didEndDisplayingCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 didDeselectItemAtIndexPath:(id)arg2;
- (_Bool)collectionView:(id)arg1 canPerformAction:(SEL)arg2 forItemAtIndexPath:(id)arg3 withSender:(id)arg4;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)manager:(id)arg1 userWillLeaveApplicationFromAdAtIndexPath:(id)arg2;
- (void)manager:(id)arg1 adAtIndexPathDidDismissScreen:(id)arg2;
- (void)manager:(id)arg1 adAtIndexPathWillDismissScreen:(id)arg2;
- (void)manager:(id)arg1 adAtIndexPathDidPresentScreen:(id)arg2;
- (void)manager:(id)arg1 adAtIndexPathWillPresentScreen:(id)arg2;
- (void)manager:(id)arg1 adDidFailToLoadAtIndexPath:(id)arg2 withError:(id)arg3;
- (void)manager:(id)arg1 didRemoveAdsAtIndexPaths:(id)arg2;
- (void)manager:(id)arg1 didLoadAdAtIndexPath:(id)arg2;
- (void)registerNibOrClassIfNecessary;
- (void)dealloc;
- (id)initWithCollectionView:(id)arg1 placementId:(long long)arg2 adPositioning:(id)arg3 collectionViewCellClass:(Class)arg4;
- (void)clearAds;
- (void)updateVisibleCells;
- (void)load;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

