//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface IMStrandPlacement : NSObject
{
    NSMutableDictionary *_desiredOriginalPositions;
    NSMutableDictionary *_desiredInsertionPositions;
    NSMutableDictionary *_originalAdIndexPaths;
    NSMutableDictionary *_revisedAdIndexPaths;
    NSMutableDictionary *_adDataObjects;
}

@property(retain, nonatomic) NSMutableDictionary *adDataObjects; // @synthesize adDataObjects=_adDataObjects;
@property(retain, nonatomic) NSMutableDictionary *revisedAdIndexPaths; // @synthesize revisedAdIndexPaths=_revisedAdIndexPaths;
@property(retain, nonatomic) NSMutableDictionary *originalAdIndexPaths; // @synthesize originalAdIndexPaths=_originalAdIndexPaths;
@property(retain, nonatomic) NSMutableDictionary *desiredInsertionPositions; // @synthesize desiredInsertionPositions=_desiredInsertionPositions;
@property(retain, nonatomic) NSMutableDictionary *desiredOriginalPositions; // @synthesize desiredOriginalPositions=_desiredOriginalPositions;
- (void).cxx_destruct;
- (void)updateSectionForPositioningArray:(id)arg1 toSection:(unsigned long long)arg2;
- (void)updateAllSectionsForPositioningArraysAtSection:(unsigned long long)arg1;
- (void)moveAllPositioningArraysInDictionariesAtSection:(unsigned long long)arg1 toSection:(unsigned long long)arg2;
- (void)clearPositioningArraysInDictionariesAtSection:(unsigned long long)arg1;
- (void)copyPositioningArrayInDictionary:(id)arg1 atSection:(unsigned long long)arg2 toSection:(unsigned long long)arg3;
- (unsigned long long)largestSectionIndexContainingAds;
- (void)decrementPlacedIndexPathsAtIndex:(unsigned long long)arg1 inSection:(unsigned long long)arg2;
- (void)decrementDesiredIndexPathsAtIndex:(unsigned long long)arg1 inSection:(unsigned long long)arg2;
- (void)incrementPlacedIndexPathsAtIndex:(unsigned long long)arg1 inSection:(unsigned long long)arg2;
- (void)incrementDesiredIndexPathsAtIndex:(unsigned long long)arg1 inSection:(unsigned long long)arg2;
- (unsigned long long)indexOfIndexPath:(id)arg1 inSortedArray:(id)arg2 options:(unsigned long long)arg3;
- (void)moveItemAtIndexPath:(id)arg1 toIndexPath:(id)arg2;
- (void)deleteItemsAtIndexPaths:(id)arg1;
- (void)insertItemsAtIndexPaths:(id)arg1;
- (void)moveSection:(long long)arg1 toSection:(long long)arg2;
- (void)deleteSections:(id)arg1;
- (void)insertSections:(id)arg1;
- (id)adDataAtRevisedIndexPath:(id)arg1;
- (id)revisedIndexPathsWithAdsInSection:(unsigned long long)arg1;
- (_Bool)isAdAtRevisedIndexPath:(id)arg1;
- (void)clearAdsInRevisedRange:(struct _NSRange)arg1 inSection:(long long)arg2;
- (id)revisedAdIndexPathsInRevisedRange:(struct _NSRange)arg1 inSection:(long long)arg2;
- (void)insertAdData:(id)arg1 atIndexPath:(id)arg2;
- (id)previousAdInsertionIndexPathForRevisedIndexPath:(id)arg1;
- (id)nextAdInsertionIndexPathForRevisedIndexPath:(id)arg1;
- (id)originalIndexPathForRevisedIndexPath:(id)arg1;
- (id)revisedIndexPathForOriginalIndexPath:(id)arg1;
- (unsigned long long)revisedNumberOfItems:(unsigned long long)arg1 inSection:(unsigned long long)arg2;
- (void)insertDesiredPositionsForIndexPath:(id)arg1;
- (void)initializeDesiredPositionsFromPositioning:(id)arg1;
- (id)positioningArrayForSection:(unsigned long long)arg1 inDictionary:(id)arg2;
- (id)initWithPositioning:(id)arg1;

@end

