//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString, UIColor, UIFont;
@protocol IMUIAction;

@interface IMUIProperties : NSObject
{
    NSString *_name;
    NSString *_type;
    UIColor *_backgroundColor;
    long long _border;
    double _borderWidth;
    UIColor *_borderColor;
    long long _corner;
    double _cornerRadius;
    UIFont *_font;
    UIColor *_textColor;
    NSString *_value;
    NSDictionary *_onClickAction;
    NSDictionary *_attributesDictionary;
    NSString *_reuseIdentifier;
    id <IMUIAction> _actionDelegate;
    struct CGRect _frame;
}

@property(nonatomic) __weak id <IMUIAction> actionDelegate; // @synthesize actionDelegate=_actionDelegate;
@property(retain, nonatomic) NSString *reuseIdentifier; // @synthesize reuseIdentifier=_reuseIdentifier;
@property(retain, nonatomic) NSDictionary *attributesDictionary; // @synthesize attributesDictionary=_attributesDictionary;
@property(retain, nonatomic) NSDictionary *onClickAction; // @synthesize onClickAction=_onClickAction;
@property(retain, nonatomic) NSString *value; // @synthesize value=_value;
@property(nonatomic) struct CGRect frame; // @synthesize frame=_frame;
@property(retain, nonatomic) UIColor *textColor; // @synthesize textColor=_textColor;
@property(retain, nonatomic) UIFont *font; // @synthesize font=_font;
@property(nonatomic) double cornerRadius; // @synthesize cornerRadius=_cornerRadius;
@property(nonatomic) long long corner; // @synthesize corner=_corner;
@property(retain, nonatomic) UIColor *borderColor; // @synthesize borderColor=_borderColor;
@property(nonatomic) double borderWidth; // @synthesize borderWidth=_borderWidth;
@property(nonatomic) long long border; // @synthesize border=_border;
@property(retain, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(retain, nonatomic) NSString *type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;

@end

