//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface IMUtilities : NSObject
{
}

+ (id)dictFromJSONData:(id)arg1;
+ (id)feedItemsFromJsonDict:(id)arg1;
+ (id)getImageURLFromBoardDict:(id)arg1;
+ (id)boardItemsFromJsonDict:(id)arg1;
+ (id)getImageURLFromNewsDict:(id)arg1;
+ (id)newsItemsFromJsonDict:(id)arg1;
+ (id)dictFromNativeContent:(id)arg1;

@end

