//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "IMNativeDelegate-Protocol.h"

@class BookShelfAdItem, IMNative, NSMutableArray, NSString;
@protocol InmobiAdUtilsDelegate;

@interface InmobiAdUtils : NSObject <IMNativeDelegate>
{
    IMNative *bookshelfFirstAdNative;
    IMNative *bookshelfFifthAdNative;
    IMNative *bookDetailAdNative;
    IMNative *lastChapterAdNative;
    IMNative *splashAdNative;
    BookShelfAdItem *bookshelfFirstAd;
    BookShelfAdItem *bookshelfFifthAd;
    BookShelfAdItem *bookDetailAd;
    BookShelfAdItem *lastChapterAd;
    BookShelfAdItem *splashAd;
    IMNative *currentReadingViewAdNative;
    BookShelfAdItem *currentReadingViewAd;
    NSMutableArray *loadedReadingViewAdNativeArr;
    _Bool bookshelfFirstAdClicked;
    _Bool bookshelfFifthAdClicked;
    _Bool bookDetailAdClicked;
    _Bool lastChapterAdClicked;
    NSMutableArray *readingViewAdClckiedArr;
    id <InmobiAdUtilsDelegate> _delegate;
}

+ (id)sharedInstance;
@property(nonatomic) __weak id <InmobiAdUtilsDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)userWillLeaveApplicationFromNative:(id)arg1;
- (void)nativeDidDismissScreen:(id)arg1;
- (void)nativeWillDismissScreen:(id)arg1;
- (void)nativeDidPresentScreen:(id)arg1;
- (void)nativeWillPresentScreen:(id)arg1;
- (void)native:(id)arg1 didFailToLoadWithError:(id)arg2;
- (void)removeClickedLog:(id)arg1;
- (void)logClickedReadingViewAdNative:(id)arg1;
- (void)addReadingViewAdNative:(id)arg1;
- (void)nativeDidFinishLoading:(id)arg1;
- (void)reportAdClickWithPositionTag:(int)arg1;
- (void)bindNativeToView:(id)arg1 withPositionTag:(int)arg2;
- (id)parseInmobiAdContent:(id)arg1;
- (id)adItemWithPositionTag:(int)arg1;
- (id)readingViewAdNative;
- (void)cleanLoadedReadingAdNative;
- (void)loadReadingViewAd;
- (void)loadInmobiNativeAdWithPositionTag:(int)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

