//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface LocalUserInfoUtils : NSObject
{
}

+ (void)updateUserBalance:(long long)arg1 voucher:(long long)arg2;
+ (long long)getUserVoucher;
+ (long long)getUserBalance;
+ (long long)getUserTotalBalanceAndVoucher;
+ (_Bool)userLoggedIn;
+ (long long)getUserExp;
+ (long long)getUserLv;
+ (id)getUserToken;
+ (id)getUserId;
+ (void)updateUserGender:(id)arg1;
+ (id)getUserGender;
+ (id)getUserGenderDisplayName;
+ (_Bool)userIsFemale;
+ (void)updateUserAvatar:(id)arg1;
+ (id)getUserAvatar;
+ (void)updateUserName:(id)arg1;
+ (id)getUserName;
+ (void)removeLocalUserInfo;
+ (void)updateLocalUserExpInfo:(id)arg1;
+ (void)setLocalUserInfo:(id)arg1;

@end

