//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseViewController.h"

#import "BookShelfViewDelegate-Protocol.h"
#import "ForumListViewDelegate-Protocol.h"

@class BookShelvesViewController, ForumListViewController, NSString, UIButton, UIImageView, UIView;
@protocol MainViewDelegate;

@interface MainViewController : BaseViewController <BookShelfViewDelegate, ForumListViewDelegate>
{
    BookShelvesViewController *bookShelfView;
    ForumListViewController *forumListView;
    UIButton *firstNavBtn;
    UIButton *secondNavBtn;
    UIView *verticalSeparator;
    UIButton *deleteBookOverView;
    _Bool bookShelfHasChanged;
    _Bool showFirstView;
    UIView *newTopicTip;
    UIImageView *newNotificationTip;
    _Bool _rightSideMenuShowed;
    _Bool _leftSideMenuShowed;
    id <MainViewDelegate> _mainViewDelegate;
}

@property(nonatomic) __weak id <MainViewDelegate> mainViewDelegate; // @synthesize mainViewDelegate=_mainViewDelegate;
@property(nonatomic) _Bool leftSideMenuShowed; // @synthesize leftSideMenuShowed=_leftSideMenuShowed;
@property(nonatomic) _Bool rightSideMenuShowed; // @synthesize rightSideMenuShowed=_rightSideMenuShowed;
- (void).cxx_destruct;
- (void)refreshAllSubviews;
- (void)onClickFirstRightItem;
- (void)onClickLeftItem;
- (void)removeNewTopicTip;
- (void)hasNewTopic:(long long)arg1;
- (void)removeNewNotificationIcon;
- (void)hasNewNotification:(id)arg1;
- (void)startMainViewNewNotificationCountRequest:(id)arg1;
- (void)bookShelfDidTriggerRefresh;
- (void)removeDeleteBookOverView;
- (void)hasBook;
- (void)bookShelfHasChanged;
- (void)viewWillAppear:(_Bool)arg1;
- (void)triggerBookshelfUpdate;
- (void)showOrHideNewTopicTip;
- (void)reloadMainView;
- (void)secondNavClicked;
- (void)firstNavClicked;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

