//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "CustomAdUtilsDelegate-Protocol.h"
#import "SKStoreProductViewControllerDelegate-Protocol.h"
#import "SelectTopicTypeViewDelegate-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class BookItem, BookShelfAdItem, CustomStatusBar, EGOImageView, MBProgressHUD, NSArray, NSDictionary, NSString, ResourceItem, UIActivityIndicatorView, UIButton, UIImage, UIImageView, UILabel, UITableView, UIView;
@protocol MenuViewDelegate;

@interface MenuViewController : UIViewController <UIGestureRecognizerDelegate, UIActionSheetDelegate, UITableViewDataSource, UITableViewDelegate, SKStoreProductViewControllerDelegate, CustomAdUtilsDelegate, SelectTopicTypeViewDelegate>
{
    UIView *headerView;
    UILabel *titleLabel;
    UIView *otherResourceView;
    NSArray *currentOtherResourceData;
    UIView *otherResourceViewSeparator;
    UIActivityIndicatorView *headerViewActivityIndicator;
    UITableView *menuViewTable;
    MBProgressHUD *progress;
    UIView *menuView;
    UIImageView *screenShotImageView;
    UIImageView *screenShotImageShadow;
    CustomStatusBar *statusBar;
    NSString *postStatusText;
    unsigned long long shareNo;
    UIView *appWrapper;
    UIButton *appBtn;
    EGOImageView *appIcon;
    UILabel *appName;
    UILabel *appIntro;
    UIImageView *maniView;
    _Bool isLandscapeMode;
    _Bool hideScreenShotAnimating;
    _Bool showNativeAd;
    UIView *footerView;
    UIActivityIndicatorView *footerViewActivityIndicator;
    NSArray *distillateBookArr;
    BookShelfAdItem *currentAdItem;
    UIView *adView;
    NSDictionary *inmobiMenuViewDic;
    UIImageView *redPoint;
    _Bool baiduAdViewDisplayed;
    UIImage *_screenShotImage;
    BookItem *_bookItem;
    id <MenuViewDelegate> _delegate;
    NSString *_lastChapterTitle;
    ResourceItem *_resourceItem;
    long long _newTopicCount;
    NSArray *_otherResourceData;
}

@property(retain, nonatomic) NSArray *otherResourceData; // @synthesize otherResourceData=_otherResourceData;
@property(nonatomic) long long newTopicCount; // @synthesize newTopicCount=_newTopicCount;
@property(retain, nonatomic) ResourceItem *resourceItem; // @synthesize resourceItem=_resourceItem;
@property(retain, nonatomic) NSString *lastChapterTitle; // @synthesize lastChapterTitle=_lastChapterTitle;
@property(nonatomic) __weak id <MenuViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) BookItem *bookItem; // @synthesize bookItem=_bookItem;
@property(retain, nonatomic) UIImage *screenShotImage; // @synthesize screenShotImage=_screenShotImage;
- (void).cxx_destruct;
- (void)customAdUtilsInmobiAdSucceedWithPositionTag:(int)arg1;
- (void)customAdUtilsBaiduAdClicked:(id)arg1;
- (void)customAdUtilsBaiduAdSucceedWithPositionTag:(int)arg1;
- (void)customAdUtilsGDTAdSucceed;
- (void)customAdUtilsGDTAdStarted:(id)arg1;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (void)refreshMenuViewWithSize:(struct CGSize)arg1;
- (void)productViewControllerDidFinish:(id)arg1;
- (void)autoSelecteRow;
- (void)backFromSelectTopicTypeView;
- (void)backToHomePage;
- (void)goSelectTopicTypeView;
- (void)goTopicSingleListView;
- (void)goSimilarBooksView;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)redPointImage;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)goBookDetailView:(id)arg1;
- (void)updateFooterView;
- (void)requestDistillateBook;
- (void)moreBookBtnClicked;
- (void)createFooterView;
- (void)changeOtherResource:(id)arg1;
- (void)addOtherSourceBtnWithItem:(id)arg1 withIndex:(int)arg2 isLast:(_Bool)arg3;
- (void)refreshHeaderViewWithData:(id)arg1;
- (void)moreResourceBtnClicked;
- (void)createHeaderView;
- (void)didReceiveMemoryWarning;
- (void)viewDidUnload;
- (void)adjustAnchorPointForGestureRecognizer:(id)arg1;
- (void)panGestureMoveAround:(id)arg1;
- (void)singleTapScreenShot:(id)arg1;
- (void)slideThenHideWithAnimationWithCompletion:(CDUnknownBlockType)arg1;
- (void)updateMenuViewAdData:(id)arg1;
- (void)startAdRequest;
- (void)updateAdView;
- (void)showAdView;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)appBtnClicked;
- (void)addAdView;
- (void)addFloatShadow;
- (id)filterCurrentResourceWithData:(id)arg1;
- (void)showSideMenu;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

