//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface MOBFImageServiceObserver : NSObject
{
    NSMutableDictionary *_listeners;
}

@property(retain, nonatomic) NSMutableDictionary *listeners; // @synthesize listeners=_listeners;
- (void).cxx_destruct;
- (void)loadingForImageURL:(id)arg1;
- (void)fail:(id)arg1 forImageURL:(id)arg2;
- (void)result:(id)arg1 forImageURL:(id)arg2;
- (void)removeAllListener;
- (void)removeListener:(id)arg1;
- (void)addListener:(CDUnknownBlockType)arg1 failHandler:(CDUnknownBlockType)arg2 loadingHandler:(CDUnknownBlockType)arg3 forImageURL:(id)arg4;
- (id)init;

@end

