//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSError;

@protocol mobideaRecProtocol

@optional
- (void)mobidea_Recs:(NSError *)arg1 feedback:(id)arg2;
@end

