//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class _priv_NBSSafeMutableDictionary;

@interface NBSLensSocketActivingHTTPs : NSObject
{
    _priv_NBSSafeMutableDictionary *activingHTTPs;
}

+ (id)sharedObject;
- (void).cxx_destruct;
- (id)findHttpsByHost:(id)arg1;
- (int)count;
- (void)removeAction:(id)arg1;
- (void)addAction:(id)arg1;
- (id)findByURL:(id)arg1;
- (id)init;
- (void)onNotification_httpFinish:(id)arg1;
- (void)onNotification_httpStart:(id)arg1;

@end

