//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NBSLensSocketConnection, NBSLensSocketWriteFuncHelper, NSString;

@interface NBSLensSocketSSLItem : NSObject
{
    int _port;
    double _handshakeStartTime;
    double _handshakeEndTime;
    long long _sslContextAddr;
    long long _sslConnectionAddr;
    long long _sendDataAddr;
    NSString *_host;
    NSString *_url;
    NBSLensSocketConnection *_socket_connection;
    NBSLensSocketWriteFuncHelper *_funcHelper;
}

@property(retain, nonatomic) NBSLensSocketWriteFuncHelper *funcHelper; // @synthesize funcHelper=_funcHelper;
@property(retain) NBSLensSocketConnection *socket_connection; // @synthesize socket_connection=_socket_connection;
@property int port; // @synthesize port=_port;
@property(retain) NSString *url; // @synthesize url=_url;
@property(retain) NSString *host; // @synthesize host=_host;
@property long long sendDataAddr; // @synthesize sendDataAddr=_sendDataAddr;
@property long long sslConnectionAddr; // @synthesize sslConnectionAddr=_sslConnectionAddr;
@property long long sslContextAddr; // @synthesize sslContextAddr=_sslContextAddr;
@property double handshakeEndTime; // @synthesize handshakeEndTime=_handshakeEndTime;
@property double handshakeStartTime; // @synthesize handshakeStartTime=_handshakeStartTime;
- (void).cxx_destruct;
- (id)init;

@end

