//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class _priv_NBSSafeMutableArray, _priv_NBSSafeMutableDictionary;

@interface NBSLensSocketConnections : NSObject
{
    _priv_NBSSafeMutableDictionary *dict_find;
    _priv_NBSSafeMutableArray *socketItems;
    _priv_NBSSafeMutableArray *logger;
}

+ (id)sharedObject;
- (void).cxx_destruct;
- (id)ssl_findSocketItemWithDataAddress:(long long)arg1;
- (id)ssl_findSocketItem:(int)arg1 ips:(id)arg2;
- (_Bool)isExist:(int)arg1;
- (id)findSocketItem:(int)arg1;
- (void)unregisterSocketItem:(int)arg1;
- (void)registerSocketItem:(id)arg1 forKey:(int)arg2;
- (id)init;

@end

