//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, _priv_NBSSafeMutableArray;

@interface NBSLensSocketConnection : NSObject
{
    long long time_connect;
    long long time_ssl;
    int refCount_connect;
    int refCount_ssl;
    _Bool _IPv6;
    int _port;
    int _isHTTP;
    NSString *_ip;
    _priv_NBSSafeMutableArray *_HTTPItems;
    double _tm1;
    long long _sendDataAddr;
}

+ (id)itemWithCopyFrom:(id)arg1;
+ (id)itemWithSocketId:(int)arg1;
@property long long sendDataAddr; // @synthesize sendDataAddr=_sendDataAddr;
@property double tm1; // @synthesize tm1=_tm1;
@property _Bool IPv6; // @synthesize IPv6=_IPv6;
@property int isHTTP; // @synthesize isHTTP=_isHTTP;
@property(readonly) _priv_NBSSafeMutableArray *HTTPItems; // @synthesize HTTPItems=_HTTPItems;
@property int port; // @synthesize port=_port;
@property(retain) NSString *ip; // @synthesize ip=_ip;
- (void).cxx_destruct;
- (void)removeHttpItem;
@property(nonatomic, getter=get_ssl, setter=set_ssl:) long long tm_d_SSLHandShake;
- (long long)pearSSLHandShakeTime;
- (long long)pearConnectTm;
@property(nonatomic, getter=get_connect, setter=set_connect:) long long tm_d_connect;
- (id)init;

@end

