//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface NBSLensSocketRawItem : NSObject
{
    int _eventType;
    int _errorCode;
    int _duration;
    NSString *_hostName;
    NSString *_ip;
    long long _port;
}

+ (id)itemWithEventType:(int)arg1;
@property int duration; // @synthesize duration=_duration;
@property int errorCode; // @synthesize errorCode=_errorCode;
@property long long port; // @synthesize port=_port;
@property(retain) NSString *ip; // @synthesize ip=_ip;
@property(retain) NSString *hostName; // @synthesize hostName=_hostName;
@property int eventType; // @synthesize eventType=_eventType;
- (void).cxx_destruct;

@end

