//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class _priv_NBSSafeMutableDictionary;

@interface NBSLensSocketDNSLogger : NSObject
{
    _priv_NBSSafeMutableDictionary *nbs_DNSCache;
    _priv_NBSSafeMutableDictionary *_NBS_IP_DNSCaches;
}

+ (id)sharedObject;
@property(retain) _priv_NBSSafeMutableDictionary *NBS_IP_DNSCaches; // @synthesize NBS_IP_DNSCaches=_NBS_IP_DNSCaches;
- (void).cxx_destruct;
- (id)findDNSItemOfHost:(id)arg1;
- (id)render;
- (void)log:(id)arg1;
- (id)init;

@end

