//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface NBSLensSocketWriteFuncHelper : NSObject
{
    CDUnknownFunctionPointerType _writeFunc;
    long long _contextAddr;
}

@property(nonatomic) long long contextAddr; // @synthesize contextAddr=_contextAddr;
@property(nonatomic) CDUnknownFunctionPointerType writeFunc; // @synthesize writeFunc=_writeFunc;
- (id)init;

@end

