//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface NBSLensSocketHTTPItem : NSObject
{
    int _sendCount;
    NSString *_ip;
    long long _port;
    long long _tm_d_connect;
    double _tm_p_firstRead;
    long long _tm_d_SSLHandShake;
    long long _tm_d_DNS;
    NSString *_url;
    double _tm_p_lastSend;
}

@property double tm_p_lastSend; // @synthesize tm_p_lastSend=_tm_p_lastSend;
@property int sendCount; // @synthesize sendCount=_sendCount;
@property(retain) NSString *url; // @synthesize url=_url;
@property long long tm_d_DNS; // @synthesize tm_d_DNS=_tm_d_DNS;
@property long long tm_d_SSLHandShake; // @synthesize tm_d_SSLHandShake=_tm_d_SSLHandShake;
@property double tm_p_firstRead; // @synthesize tm_p_firstRead=_tm_p_firstRead;
@property long long tm_d_connect; // @synthesize tm_d_connect=_tm_d_connect;
@property long long port; // @synthesize port=_port;
@property(retain) NSString *ip; // @synthesize ip=_ip;
- (void).cxx_destruct;
- (id)init;

@end

