//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSString;

@interface ProductItem : NSObject <NSCoding>
{
    NSString *_productItemId;
    long long _price;
    long long _currency;
    long long _voucher;
    NSString *_productId;
}

@property(retain, nonatomic) NSString *productId; // @synthesize productId=_productId;
@property(nonatomic) long long voucher; // @synthesize voucher=_voucher;
@property(nonatomic) long long currency; // @synthesize currency=_currency;
@property(nonatomic) long long price; // @synthesize price=_price;
@property(retain, nonatomic) NSString *productItemId; // @synthesize productItemId=_productItemId;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)setValue:(id)arg1 forUndefinedKey:(id)arg2;
- (id)initWithDictionary:(id)arg1;

@end

