//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseViewController.h"

#import "SKStoreProductViewControllerDelegate-Protocol.h"
#import "ShareSDKViewDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class AFHTTPRequestOperation, EGOImageView, NSArray, NSDictionary, NSString, NotificationCountItem, ShareSDKUtils, UIButton, UILabel, UITableView, UIView;

@interface ProfileViewController : BaseViewController <ShareSDKViewDelegate, UITableViewDataSource, UITableViewDelegate, SKStoreProductViewControllerDelegate>
{
    ShareSDKUtils *shareSDKUtils;
    UITableView *profileTableView;
    EGOImageView *avatar;
    UILabel *userName;
    NSArray *commissionArr;
    NSArray *funcArr;
    UILabel *userLevel;
    UIView *experienceCurrentBg;
    UILabel *experienceLabel;
    NSDictionary *detailInfo;
    AFHTTPRequestOperation *requestCanCancel;
    NSArray *msgBookListArray;
    NSArray *mineMsgArray;
    NSArray *imageIconArray;
    UIView *footerView;
    UIButton *exitBtn;
    NotificationCountItem *_notificationCountItem;
}

@property(retain, nonatomic) NotificationCountItem *notificationCountItem; // @synthesize notificationCountItem=_notificationCountItem;
- (void).cxx_destruct;
- (void)refreshAllSubviews;
- (void)progressHideWithCancelBtn;
- (void)onClickFirstRightItem;
- (void)onClickLeftItem;
- (long long)calculateLevelExp:(long long)arg1;
- (void)productViewControllerDidFinish:(id)arg1;
- (void)updateBookshelfSucceed;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)refreshThemeColor;
- (void)viewWillAppear:(_Bool)arg1;
- (void)setImageAndAddLabel:(id)arg1 text:(id)arg2;
- (void)createFooterView;
- (void)refreshHeaderView;
- (void)createHeaderView;
- (void)goMoreFuncView;
- (void)goWeChatPublicView;
- (void)goMyTaskView;
- (void)goExperienceLevelView;
- (void)goBookListView;
- (void)goCollectedBookListView;
- (void)goTopicView;
- (void)goMyNotificationView;
- (void)reloadProfileView;
- (void)startGetUserDetailInfoRequest;
- (void)setUILabelProperty:(id)arg1;
- (void)goAccountView;
- (void)goEditProfileView;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

