//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIControl.h>

@class NSDate, UIImage;

@interface RCSwitch : UIControl
{
    UIImage *knobImage;
    UIImage *knobImagePressed;
    UIImage *sliderOff;
    UIImage *sliderOn;
    UIImage *buttonEndTrack;
    UIImage *buttonEndTrackPressed;
    float percent;
    float oldPercent;
    float knobWidth;
    float endcapWidth;
    struct CGPoint startPoint;
    float scale;
    float drawHeight;
    float animationDuration;
    struct CGSize lastBoundsSize;
    NSDate *endDate;
    _Bool mustFlip;
}

- (void).cxx_destruct;
- (void)performSwitchToPercent:(float)arg1;
- (void)setOn:(_Bool)arg1 animated:(_Bool)arg2;
@property(getter=isOn) _Bool on;
- (void)endTrackingWithTouch:(id)arg1 withEvent:(id)arg2;
- (void)cancelTrackingWithEvent:(id)arg1;
- (void)finishEvent;
- (_Bool)continueTrackingWithTouch:(id)arg1 withEvent:(id)arg2;
- (_Bool)beginTrackingWithTouch:(id)arg1 withEvent:(id)arg2;
- (void)drawRect:(struct CGRect)arg1;
- (void)drawUnderlayersInRect:(struct CGRect)arg1 withOffset:(float)arg2 inTrackWidth:(float)arg3;
- (void)regenerateImages;
@property float knobWidth;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)initCommon;

@end

