//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RCSwitch.h"

@class UILabel;

@interface RCSwitchOnOff : RCSwitch
{
    UILabel *onText;
    UILabel *offText;
}

- (void).cxx_destruct;
- (void)drawUnderlayersInRect:(struct CGRect)arg1 withOffset:(float)arg2 inTrackWidth:(float)arg3;
- (void)initCommon;

@end

