//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface ReadingUtils : NSObject
{
}

+ (void)changeReadingModeWithBookItem:(id)arg1 chapterItem:(id)arg2 resourceName:(id)arg3 chapterNum:(long long)arg4 fromVC:(id)arg5;
+ (int)getReadingModeTagWithResourceName:(id)arg1;
+ (void)goOriginResourceView:(id)arg1 fromVC:(id)arg2 resourceItem:(id)arg3;
+ (void)goReadingViewDirectly:(id)arg1 fromVC:(id)arg2 resourceItem:(id)arg3 chapterNum:(long long)arg4 needReloadDirectory:(_Bool)arg5 needDelayRequest:(_Bool)arg6 needFlipHorizontal:(_Bool)arg7;
+ (id)getLastReadSourceIdFromMixReadingWithBookId:(id)arg1;
+ (id)getLastReadSourceNameFromMixReadingWithBookId:(id)arg1;
+ (_Bool)goReadingView:(id)arg1 fromVC:(id)arg2 isSecondaryView:(_Bool)arg3 needGoDirectly:(_Bool)arg4;

@end

