//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "BaiFenDianUtilsDelegate-Protocol.h"
#import "ReadingCpModelDelegate-Protocol.h"
#import "ReadingModelDelegate-Protocol.h"

@class AFHTTPRequestOperation, NSString, ReadingModel;
@protocol ReadingViewManagerDelegate;

@interface ReadingViewManager : NSObject <BaiFenDianUtilsDelegate, ReadingModelDelegate, ReadingCpModelDelegate>
{
    ReadingModel *readingModel;
    AFHTTPRequestOperation *requestCanCancel;
    NSString *_bookId;
    id <ReadingViewManagerDelegate> _delegate;
}

@property(nonatomic) __weak id <ReadingViewManagerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSString *bookId; // @synthesize bookId=_bookId;
- (void).cxx_destruct;
- (void)RCM_needPurchaseChapter;
- (void)RCM_needShowPurchaseView;
- (void)RCM_needUpdateChapterKeysDicWithDic:(id)arg1;
- (void)RM_needUpdatePageParams;
- (void)RM_needUpdateLoadingDirectoryStatus:(int)arg1;
- (void)RM_needUpdateRequest:(id)arg1;
- (void)RM_needShowCustomLoadingProgressWithCancelBtn:(_Bool)arg1;
- (void)recommendRequestFinishedWithBookItem:(id)arg1;
- (void)resetReadingRandomWithErrorStatus:(int)arg1;
- (void)startReadingRandomDirectoryAndChapterRequestWithBookId:(id)arg1;
- (void)startReadingRandomRequest;
- (void)resetReadingViewWithErrorStatus:(int)arg1 turnToMaxIndex:(_Bool)arg2;
- (void)triggerRequestChapterData:(_Bool)arg1;
- (void)cancelRequest;
- (id)parseChapterData:(id)arg1;
- (void)startGetChapter:(CDUnknownBlockType)arg1;
- (void)startGetDirectory:(CDUnknownBlockType)arg1;
- (void)resetReadingModel;
- (void)setupReadingModel;
- (void)getResourceItem:(CDUnknownBlockType)arg1;
- (void)startChapterRequset;
- (void)startDirectoryAndChapterRequest;
- (void)startReadingRequest;
- (id)init;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

