//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ReadingModel.h"

@protocol ReadingCpModelDelegate;

@interface ReadingCpModel : ReadingModel
{
}

- (id)parseChapterKeysData:(id)arg1 withLocalKeys:(id)arg2;
- (void)replaceServerChapterKeysToLocal:(id)arg1;
- (void)reloadNormalDirectoryDataFromServerWithBlock:(CDUnknownBlockType)arg1;
- (void)loadNormalDirectoryDataFromServerWithBlock:(CDUnknownBlockType)arg1;
- (id)getLocalDirectoryData;
- (void)decryptCpChapterWithBlock:(CDUnknownBlockType)arg1;
- (void)getChapterDataWithBlock:(CDUnknownBlockType)arg1;
- (void)getBookDirecotryWithBlock:(CDUnknownBlockType)arg1;

// Remaining properties
@property(nonatomic) __weak id <ReadingCpModelDelegate> delegate; // @dynamic delegate;

@end

