//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "AVSpeechSynthesizerDelegate-Protocol.h"
#import "IFlySpeechSynthesizerDelegate-Protocol.h"
#import "UIAlertViewDelegate-Protocol.h"

@class AVSpeechSynthesizer, AVSpeechUtterance, IFlySpeechSynthesizer, NSMutableArray, NSString, ReadViewLabel, ReadingInfoItem;
@protocol ReadingAloudManagerDelegate;

@interface ReadingAloudManager : NSObject <AVSpeechSynthesizerDelegate, IFlySpeechSynthesizerDelegate, UIAlertViewDelegate>
{
    NSMutableArray *paragraphArray;
    NSMutableArray *rangeArray;
    NSString *nextPageFirstParagraph;
    NSString *appendStr;
    int lastParagraphProgress;
    AVSpeechUtterance *avSpeechUtterance;
    long long currentParagraphNo;
    _Bool isPause;
    _Bool isChangingPage;
    AVSpeechSynthesizer *avSpeechSynthesizer;
    IFlySpeechSynthesizer *iFlySpeechSynthesizer;
    id <ReadingAloudManagerDelegate> _delegate;
    ReadViewLabel *_readViewLabel;
    ReadingInfoItem *_readingInfoItem;
}

+ (id)sharedInstance;
@property(retain, nonatomic) ReadingInfoItem *readingInfoItem; // @synthesize readingInfoItem=_readingInfoItem;
@property(retain, nonatomic) ReadViewLabel *readViewLabel; // @synthesize readViewLabel=_readViewLabel;
@property(nonatomic) __weak id <ReadingAloudManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)configNowPlayingInfoCenter;
- (void)readAloudBackForegroundPlay;
- (void)readAloudForBackgroundPlay;
- (void)readAloudChangeSlowSpeed;
- (void)readAloudChangeFastSpeed;
- (void)speechSynthesizer:(id)arg1 didCancelSpeechUtterance:(id)arg2;
- (void)speechSynthesizer:(id)arg1 willSpeakRangeOfSpeechString:(struct _NSRange)arg2 utterance:(id)arg3;
- (void)speechSynthesizer:(id)arg1 didFinishSpeechUtterance:(id)arg2;
- (void)stopAppleSpeech;
- (void)startAppleSpeechWithMsg:(id)arg1;
- (void)onSpeakProgress:(int)arg1;
- (void)onBufferProgress:(int)arg1 message:(id)arg2;
- (void)onCompleted:(id)arg1;
- (void)stopIFlySpeech;
- (void)startIFlySpeechWithMsg:(id)arg1;
- (void)changeSpeechSpeed;
- (void)triggerChangeSpeechType;
- (void)updateReadingViewWithMsg:(id)arg1;
- (void)cancelSpeech;
- (void)stopSpeech;
- (void)resumeSpeech;
- (void)pauseSpeech;
- (void)startSpeech;
- (id)getReadingAloudVoiceTypes;
- (void)parseSpeechContentWithPageItem:(id)arg1 pageNum:(long long)arg2;
- (void)startSpeechWithPageItem:(id)arg1 pageNum:(long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

