//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "AutoReadingViewDelegate-Protocol.h"
#import "BookDirectoryDelegate-Protocol.h"
#import "CachedChapterModelDelegate-Protocol.h"
#import "ChangeResourceViewDelegate-Protocol.h"
#import "CustomAdUtilsDelegate-Protocol.h"
#import "EmailLoginViewControllerDelegate-Protocol.h"
#import "MBProgressHUDDelegate-Protocol.h"
#import "MenuViewDelegate-Protocol.h"
#import "ReadingAloudManagerDelegate-Protocol.h"
#import "ReadingChangeModeViewDelegate-Protocol.h"
#import "ReadingErrorViewDelegate-Protocol.h"
#import "ReadingMoreSettingDelegate-Protocol.h"
#import "ReadingPageModelDelegate-Protocol.h"
#import "ReadingPurchaseDelegate-Protocol.h"
#import "ReadingScrollManagerDelegate-Protocol.h"
#import "ReadingToolsViewDelegate-Protocol.h"
#import "ReadingViewManagerDelegate-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"
#import "UIAlertViewDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"

@class AFHTTPRequestOperation, AutoReadingView, BookItem, CachedChapterModel, CutPage, CutPageItem, EmailLoginViewController, MBProgressHUD, MenuViewController, NSArray, NSString, ReadingChangeModeView, ReadingErrorView, ReadingPageModel, ReadingPurchaseView, ReadingScrollManager, ReadingToolsView, ReadingViewManager, UIButton, UpdateReadingLogModel;
@protocol ReadingViewControllerDelegate;

@interface ReadingViewController : UIViewController <MBProgressHUDDelegate, UIAlertViewDelegate, UIActionSheetDelegate, ReadingChangeModeViewDelegate, ReadingErrorViewDelegate, ReadingToolsViewDelegate, UIScrollViewDelegate, BookDirectoryDelegate, ReadingMoreSettingDelegate, ReadingPurchaseDelegate, ReadingPageModelDelegate, CachedChapterModelDelegate, ReadingViewManagerDelegate, ChangeResourceViewDelegate, AutoReadingViewDelegate, ReadingScrollManagerDelegate, CustomAdUtilsDelegate, EmailLoginViewControllerDelegate, ReadingAloudManagerDelegate, MenuViewDelegate>
{
    UIButton *guideImageBtn;
    _Bool loadSuccess;
    CutPage *cutPage;
    CutPageItem *currentCutPageItem;
    MBProgressHUD *progress;
    AFHTTPRequestOperation *requestCanCancel;
    int loadingDirectory;
    ReadingErrorView *readingErrorView;
    ReadingToolsView *readingToolsView;
    ReadingPurchaseView *readingPurchaseView;
    long long newTopicCount;
    NSArray *otherResourceData;
    _Bool isLandscapeMode;
    MenuViewController *menuViewController;
    _Bool finalPageTriggered;
    _Bool purchaseViewShowed;
    long long prepayChapterNum;
    _Bool errorViewShowed;
    CachedChapterModel *cachedChapterModel;
    ReadingPageModel *readingPageModel;
    UpdateReadingLogModel *updateReadingLogModel;
    ReadingViewManager *readingViewManager;
    ReadingScrollManager *readingScrollManager;
    _Bool isFromDirectoryView;
    _Bool isFromChangeResourceView;
    ReadingChangeModeView *readingChangeModeView;
    AutoReadingView *autoReadingView;
    _Bool requestByAutoReadingViewStarted;
    NSString *oldCustomFontName;
    struct CGRect statusBarRect;
    long long readedChapterCount;
    _Bool isAutoReadingNextPage;
    _Bool isGetNextPage;
    _Bool isGDTAd;
    EmailLoginViewController *emailLoginView;
    _Bool _isRandomMode;
    _Bool _needDelayRequest;
    _Bool _isMixReadingMode;
    _Bool _dontResetChapterNum;
    _Bool _needResetPageNum;
    BookItem *_bookItem;
    NSString *_lastResourceChapterTitle;
    long long _lastResourceChapterNum;
    id <ReadingViewControllerDelegate> _delegate;
}

@property(nonatomic) __weak id <ReadingViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) long long lastResourceChapterNum; // @synthesize lastResourceChapterNum=_lastResourceChapterNum;
@property(retain, nonatomic) NSString *lastResourceChapterTitle; // @synthesize lastResourceChapterTitle=_lastResourceChapterTitle;
@property(nonatomic) _Bool needResetPageNum; // @synthesize needResetPageNum=_needResetPageNum;
@property(nonatomic) _Bool dontResetChapterNum; // @synthesize dontResetChapterNum=_dontResetChapterNum;
@property(nonatomic) _Bool isMixReadingMode; // @synthesize isMixReadingMode=_isMixReadingMode;
@property(nonatomic) _Bool needDelayRequest; // @synthesize needDelayRequest=_needDelayRequest;
@property(nonatomic) _Bool isRandomMode; // @synthesize isRandomMode=_isRandomMode;
@property(retain, nonatomic) BookItem *bookItem; // @synthesize bookItem=_bookItem;
- (void).cxx_destruct;
- (void)customAdUtilsBaiduAdClicked:(id)arg1;
- (void)customAdUtilsGDTAdSucceed;
- (void)customAdUtilsGDTAdStarted:(id)arg1;
- (id)getCurentViewReadViewLabel;
- (void)RAM_showToastWithMsg:(id)arg1;
- (void)RAM_exitReadingAloud;
- (void)RAM_changeSpeedSlow;
- (void)RAM_changeSpeedFast;
- (void)RAM_speechTypeChanged;
- (void)RAM_speechCancelled;
- (void)RAM_speechPaused;
- (void)RAM_speechStarted;
- (void)RAM_clearReadViewLabelTag;
- (void)RAM_getNextPage;
- (void)needStartSpeakingByDefault;
- (void)needShowBookDirectoryViewWithDirectoryData:(id)arg1 resourceItem:(id)arg2;
- (void)needReloadReadingViewWithChapterNum:(long long)arg1;
- (void)RSM_speechTypeChanged;
- (void)RSM_speechCancelled;
- (void)RSM_speechPaused;
- (void)RSM_speechStarted;
- (void)RSM_changeSpeedSlow;
- (void)RSM_changeSpeedFast;
- (void)RSM_cutPageOnclickShowRemitAdView;
- (void)RSM_cutPageOnClickShowAd:(id)arg1;
- (void)RSM_showInmobiAd;
- (void)RSM_showGDTAd;
- (void)RSM_needPreCache;
- (void)RSM_needRefreshNextPageWithChapterNum:(long long)arg1;
- (void)RSM_needRefreshPrePageWithChapterNum:(long long)arg1;
- (void)RSM_needShowMenuViewController;
- (void)RSM_needShowToastWithStr:(id)arg1;
- (void)RSM_needFinishCustomLoadingProgress;
- (void)RSM_needShowCustomLoadingProgress;
- (void)needAddReadErrorViewWithStatus:(int)arg1;
- (void)needRemoveErrorView;
- (void)needEnableAddToBookshelfBtn:(_Bool)arg1;
- (void)needEnableChangeBookBtn:(_Bool)arg1;
- (void)needHideToolsView;
- (void)needResetBookshelfBtn;
- (void)needUpdateChapterKeysDicWithDic:(id)arg1;
- (void)needPurchaseChapter;
- (void)needHidePurchaseView;
- (void)needShowPurchaseView;
- (void)needResetBookItem:(id)arg1;
- (void)needResetReadingViewWithErrorStatus:(int)arg1 resourceUrlStr:(id)arg2 maxIndex:(_Bool)arg3;
- (void)needReloadReadingViewWithTurnToMaxIndex:(_Bool)arg1;
- (void)needShowCustomLoadingProgressWithCancelBtn:(_Bool)arg1;
- (void)needUpdatePageParams;
- (void)needUpdateLoadingDirectoryStatus:(int)arg1;
- (void)needRemoveAllCachedObjects;
- (void)prePayNextChapter;
- (void)needPrepayNextChapter;
- (void)modelNeedUpdatedWithChapterItem:(id)arg1 chapterNum:(long long)arg2;
- (void)needSetCacheWithChapterItem:(id)arg1 dicData:(id)arg2 cachedNum:(long long)arg3;
- (void)resetReadingViewWithTmpChapter:(id)arg1;
- (void)resetReadingViewWithCachedChapterItemWithMaxIndex:(_Bool)arg1;
- (void)refreshPagePreViewWithChapterNum:(long long)arg1 maxIndex:(_Bool)arg2;
- (void)RPM_showInmobiAd;
- (void)RPM_showGDTAd;
- (void)RPM_readingAloudNeedExit;
- (void)RPM_readingAloudNeedSpeak;
- (void)RPM_cutPageOnclickShowRemitAdView;
- (void)RPM_cutPageOnClickShowAd:(id)arg1;
- (void)needDecreaseReadedChapterCount;
- (void)needIncreaseReadedChapterCount;
- (void)RPM_needShowMenuViewController;
- (void)RPM_needShowToastWithStr:(id)arg1;
- (void)RPM_needFinishCustomLoadingProgress;
- (void)RPM_needShowCustomLoadingProgress;
- (void)needEnableUserInteraction;
- (void)needDisableUserInteraction;
- (void)pageControllerDidSwitched;
- (void)pageControllerWillSwitch;
- (void)needRefreshNextPagePreViewWithChapterNum:(long long)arg1;
- (void)needRefreshLastPagePreViewWithChapterNum:(long long)arg1;
- (void)RPM_needPreCache;
- (void)needUpdateCurrentCutPageItem:(id)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotate;
- (void)needGoToRewardView;
- (void)needFeedbackErrMsg:(id)arg1;
- (void)needGoToWeiXinView;
- (void)refreshReadingView;
- (void)rotateScreenByOrientation:(long long)arg1 animated:(_Bool)arg2 refresh:(_Bool)arg3;
- (void)rotateScreenIfNeeded;
- (void)forceRotateScreen;
- (void)needRotate;
- (void)needStartRandomReading;
- (void)needDetectNetworkStatus;
- (void)needGoDirectoryView;
- (void)needGoChangeResourceView_RTV;
- (void)needGoMoreSettingView;
- (void)needGoForum;
- (void)needGoOriginResourceView;
- (void)needGoBack;
- (void)needShowChangeReadingModeView;
- (void)needReloadReadingView;
- (void)needInitializeToolsView;
- (void)triggerHorizontalPanGestureWithTranslation:(struct CGPoint)arg1;
- (void)triggerVerticalPanGestureWithTranslation:(struct CGPoint)arg1;
- (void)panGestureTriggered:(id)arg1;
- (_Bool)detectTouchedMiddlePage:(struct CGPoint)arg1;
- (_Bool)detectTouchedPrevPageDefaultRegion:(struct CGPoint)arg1;
- (_Bool)detectTouchedPrevPage:(struct CGPoint)arg1;
- (_Bool)detectTouchedNextPageDefaultRegion:(struct CGPoint)arg1;
- (_Bool)detectTouchedNextPage:(struct CGPoint)arg1;
- (_Bool)reachedFirstPage;
- (_Bool)reachedFinalPage;
- (void)tapGestureTriggered:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)hideToolsView;
- (void)showToolsView;
- (void)touchedMiddlePage;
- (void)showMenuViewController;
- (void)waitDirectoryRequestFinish;
- (void)touchedNextPageByTapGesture:(_Bool)arg1;
- (void)touchedPrevPage;
- (void)changeBtnClickedWithErrorStatus:(int)arg1;
- (void)didSelectReadingModeWithResourceName:(id)arg1;
- (void)didHideReadingModeView;
- (void)willHideReadingModeView;
- (void)willShowReadingModeView;
- (void)removeReadingErrorView;
- (void)addReadingErrorViewWithStatus:(int)arg1;
- (void)ELVC_loginSucceed;
- (void)hidePurchaseView;
- (void)showPurchaseView;
- (void)RPV_needShowEmailLoginView;
- (void)RPV_needFinishCustomLoadingProgress;
- (void)RPV_needShowCustomLoadingProgress;
- (void)pvChangeSourceBtnClicked;
- (void)pvChargeBtnClicked;
- (void)pvLoginSucceed;
- (void)purchaseFailedWithPrepay:(_Bool)arg1;
- (void)purchaseSucceedWithPrepay:(_Bool)arg1;
- (void)hudCustomAnimationDone;
- (void)cancelOtherRequest;
- (void)hudWasHiddenByCancelBtn;
- (void)showPreviewOption;
- (void)detectNetworkStatus;
- (void)getDownloadingProgress:(id)arg1;
- (void)downloadChapterWithTag:(int)arg1;
- (void)addDownloadObserver;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)needGoChangeResourceView_MVC;
- (void)needChangeReadingViewWithResourceItem:(id)arg1;
- (void)backFromMenuView;
- (void)backToHomePage;
- (void)didSwitchTraditionalMode;
- (void)didSwitchPageTransitionStyle;
- (void)goRemitAdView;
- (void)goAdViewWithItem:(id)arg1;
- (void)goMenuViewController;
- (void)goMoreSettingView;
- (void)goDirectoryView;
- (void)goChangeResourceView;
- (void)goBack;
- (void)goForum;
- (void)showReadingChangeModeView;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (void)chapterNumAndPageNumInitialize;
- (void)pageParamsInitialize;
- (void)ARV_needRequestPreChapter;
- (void)ARV_needRequestNextChapter;
- (void)ARV_needPreCache;
- (void)autoReadingFinishedWithChapterIndex:(long long)arg1 pageIndex:(long long)arg2;
- (void)needStartAutoReading;
- (void)autoReadingViewInitialize;
- (void)requestBookHasRewardFeature;
- (void)readingToolsViewInitialize;
- (void)enableGestures;
- (void)disableGestures;
- (void)addGestures;
- (void)readingViewInitialize;
- (void)updateModelWithBookItem;
- (void)updateModelWithCachedChapterModel;
- (void)modelAndManagerInitialize;
- (void)changeStatusBarFrame:(id)arg1;
- (void)addStatusBarObserver;
- (void)handleAudioSessionChanged:(id)arg1;
- (void)addAudioSessionRouteChangeObserver;
- (void)handleInterruption:(id)arg1;
- (void)applicationWillResignActive;
- (void)applicationWillEnterForeground;
- (void)addSaveBookObserver;
- (void)hideProgressIfExist;
- (_Bool)detectIsMixReadingMode;
- (void)finishAndHideProgress;
- (void)showToastWithMsg:(id)arg1 duration:(double)arg2;
- (void)showToastWithMsg:(id)arg1;
- (void)showProgressWithCancelBtn:(_Bool)arg1;
- (id)getTopParentViewController:(id)arg1 withBackBtnClicked:(_Bool)arg2;
- (void)customGoBackWithClicked:(_Bool)arg1 withAnimate:(_Bool)arg2 withResourceName:(id)arg3;
- (void)saveBookReadingLog;
- (void)viewWillDisappear:(_Bool)arg1;
- (_Bool)customFontDidChanged;
- (void)didReceiveMemoryWarning;
- (void)removeGuide;
- (void)addGuide;
- (void)startOtherResourceDataRequest;
- (void)startNewTopicRequest;
- (void)readingParamsInitialize;
- (void)startLoadRequest;
- (void)addMenuViewToBack;
- (void)logReadingMode;
- (void)startReadingViewAdRequest;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

