//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UIAlertViewDelegate-Protocol.h"

@class NSArray, NSDate, NSMutableArray, NSObject, NSString, UIButton, UIImageView, UILabel, UIScrollView, UISlider;
@protocol OS_dispatch_source, ReadingToolsViewDelegate;

@interface ReadingToolsView : UIView <UIAlertViewDelegate>
{
    UIView *topView;
    UIImageView *bottomView;
    UIView *settingView;
    UIView *settingViewSubWrapper;
    UIView *downloadView;
    UILabel *downloadProgressLabel;
    UIView *blackView;
    UIButton *changeRotationBtn;
    UIButton *originResourceBtn;
    UILabel *resourceUrl;
    NSString *resourceUrlStr;
    UILabel *resourceEnter;
    UIView *bottomViewSubViewWrapper;
    UIButton *dayAndNightMode;
    UIButton *whiteModeBtn;
    UIButton *yellowModeBtn;
    UIButton *greenModeBtn;
    UILabel *bookNameLabel;
    UILabel *randomTitle;
    UIButton *addToBookshelfBtn;
    UIButton *changeBookBtn;
    NSString *locationString;
    NSMutableArray *contentIdArray;
    NSMutableArray *dataArray;
    UIButton *decreaseFontBtn;
    UIButton *increaseFontBtn;
    UISlider *luminanceSlider;
    UIButton *autoReadingBtn;
    UIButton *moreSettingBtn;
    UIButton *forumBtn;
    UIButton *readAloudBtn;
    UIButton *backBtn;
    int nowFontSize;
    _Bool fontSettingShowed;
    UIButton *changeModeBtn;
    UIImageView *arrowDownImage;
    UIView *luminanceSliderViewWrapper;
    UIView *setFontViewWrapper;
    UIView *setReadingBgViewWrapper;
    _Bool canRotate;
    UIView *readingAloudView;
    UIView *readingAloudWrapperView;
    UISlider *speechSpeedSlider;
    NSMutableArray *readingAloudTypeArray;
    NSArray *timerArray;
    UIView *speechSpeedWrapperView;
    UIScrollView *showReadingAloudTypeScrollView;
    UIView *timerView;
    UIButton *pauseBtn;
    UIButton *readingAloudOverViewBtn;
    NSObject<OS_dispatch_source> *_timer;
    _Bool isSpeaking;
    NSDate *beginDate;
    NSDate *endDate;
    UIButton *shadowBtn;
    UIView *firstFloorView;
    UIButton *bookError;
    UIButton *adviseBtn;
    UILabel *sepaLabel;
    UIView *secondFloorView;
    NSArray *secondMenuArray;
    UIButton *changeDirectionBtn;
    UIView *readAloudTypeView;
    UIButton *exitBtn;
    UIView *readAloudBottomView;
    UIButton *rewardBtn;
    UIImageView *rewardImageView;
    UIImageView *launchRewardImageView;
    _Bool _isRandomMode;
    _Bool _dontHideStatusBar;
    _Bool _settingViewShowed;
    _Bool _readAloudViewShowed;
    _Bool _readAloudModeEnable;
    _Bool _isMixReadingMode;
    NSString *_bookId;
    id <ReadingToolsViewDelegate> _delegate;
    struct CGRect _statusBarRect;
}

+ (_Bool)readingAloudEnable;
@property(nonatomic) __weak id <ReadingToolsViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) struct CGRect statusBarRect; // @synthesize statusBarRect=_statusBarRect;
@property(nonatomic) _Bool isMixReadingMode; // @synthesize isMixReadingMode=_isMixReadingMode;
@property(nonatomic) _Bool readAloudModeEnable; // @synthesize readAloudModeEnable=_readAloudModeEnable;
@property(nonatomic) _Bool readAloudViewShowed; // @synthesize readAloudViewShowed=_readAloudViewShowed;
@property(nonatomic) _Bool settingViewShowed; // @synthesize settingViewShowed=_settingViewShowed;
@property(nonatomic) _Bool dontHideStatusBar; // @synthesize dontHideStatusBar=_dontHideStatusBar;
@property(nonatomic) _Bool isRandomMode; // @synthesize isRandomMode=_isRandomMode;
@property(retain, nonatomic) NSString *bookId; // @synthesize bookId=_bookId;
- (void).cxx_destruct;
- (void)onClickSendFeedback:(id)arg1;
- (void)onClickShowAdviseView;
- (void)onClickShowSecondFloorView;
- (void)onClickHideShadowBtn:(id)arg1;
- (void)showFeedbackSecondView;
- (void)showFeedbackFirstView;
- (void)reloadReadingView;
- (void)refreshSettingView;
- (void)refreshForumBtnAndBottomView;
- (void)refreshOriginResourceView;
- (void)refreshTopView;
- (void)refreshTitleView;
- (void)changeRewardView;
- (void)refreshToolsViewWithStatus:(_Bool)arg1 animate:(_Bool)arg2;
- (void)changeModeTitleToMixReading;
- (void)updateDownloadProgressLabelText:(id)arg1;
- (void)showDownloadProgressView;
- (void)showToolsViewWithAnimate:(_Bool)arg1;
- (void)hideToolsViewWithAnimate:(_Bool)arg1;
- (void)onClickShowTimeDownCount:(id)arg1 btn:(id)arg2;
- (void)onClickExitReadAloud;
- (void)onClickTimerCountDown:(id)arg1;
- (void)onClickReadingAloudTypeBtn:(id)arg1;
- (void)changeSpeedSlow;
- (void)changeSpeedFast;
- (void)speedProgressChange:(id)arg1;
- (void)resetSpeechTypeBtns;
- (void)resetPauseBtnWithStatusOn:(_Bool)arg1;
- (void)onClickPause:(id)arg1;
- (void)setReadingAloudView;
- (void)lightProgressChange:(id)arg1;
- (void)setBtnSelected;
- (void)nightModeChange;
- (void)dayModeChange:(id)arg1;
- (void)increaseFont:(id)arg1;
- (void)decreaseFont:(id)arg1;
- (void)changeFontSize:(_Bool)arg1;
- (void)refreshReadingAloudView;
- (void)changeReadAloudViewShowStatus;
- (void)showOrHiddenAloudView;
- (void)onClickShowAloudView:(id)arg1;
- (void)showSettingView;
- (void)setBtnProperty:(id)arg1;
- (void)removeFromBookshelf;
- (void)addToBookshelf;
- (void)addToBookshelfClicked;
- (void)enableAddToBookshelfBtn:(_Bool)arg1;
- (void)enableChangeBookBtn:(_Bool)arg1;
- (void)resetBookShefBtn;
- (void)setRandomBottomView;
- (void)setTitlePropertyToBottomBtn:(id)arg1;
- (void)setBottomSubViewWrapperFrame;
- (void)setNormalBottomView;
- (void)openOriginResourceView;
- (void)setResourceUrlText:(id)arg1;
- (void)addResourceUrlView;
- (void)toggleArrowDownRotation;
- (id)createHighlightedImageWithTitle:(id)arg1;
- (id)createNormalImageWithTitle:(id)arg1;
- (void)hideRewardView;
- (void)showRewardView;
- (void)addRewardView;
- (void)addTopAndBottomTools;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

