//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol ReadingPurchaseDelegate <NSObject>

@optional
- (void)RPV_needShowEmailLoginView;
- (void)RPV_needFinishCustomLoadingProgress;
- (void)RPV_needShowCustomLoadingProgress;
- (void)needUpdatePurchaseViewShowed:(_Bool)arg1;
- (void)pvChargeBtnClicked;
- (void)pvChangeSourceBtnClicked;
- (void)pvLoginSucceed;
- (void)purchaseFailedWithPrepay:(_Bool)arg1;
- (void)purchaseSucceedWithPrepay:(_Bool)arg1;
@end

