//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString;

@protocol ReadingToolsViewDelegate <NSObject>

@optional
- (void)needStartSpeakingByDefault;
- (void)needGoToRewardView;
- (void)needFeedbackErrMsg:(NSString *)arg1;
- (void)needGoToWeiXinView;
- (void)needPauseSpeakingByTimeOut;
- (void)needStartSpeaking;
- (void)needStartAutoReading;
- (void)needRotate;
- (void)needStartRandomReading;
- (void)needDetectNetworkStatus;
- (void)needGoDirectoryView;
- (void)needGoChangeResourceView_RTV;
- (void)needGoMoreSettingView;
- (void)needGoForum;
- (void)needGoOriginResourceView;
- (void)needGoBack;
- (void)needShowChangeReadingModeView;
- (void)needReloadReadingView;
@end

