//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseViewController.h"

#import "MFMailComposeViewControllerDelegate-Protocol.h"
#import "TraceRouteDelegate-Protocol.h"
#import "UITextViewDelegate-Protocol.h"

@class NSString, NSTimer, TraceRouteUtils, UITextView;

@interface ReportNetworkViewController : BaseViewController <UITextViewDelegate, TraceRouteDelegate, MFMailComposeViewControllerDelegate>
{
    UITextView *networkReportView;
    TraceRouteUtils *traceRouteUtils;
    _Bool hideReport;
    NSTimer *changeProgressTimer;
    long long progressTextIndex;
}

- (void).cxx_destruct;
- (void)onClickFirstRightItem;
- (void)onClickLeftItem;
- (void)updateReportViewWithRecord:(id)arg1;
- (void)receiveNewRecord:(id)arg1;
- (void)reportFinished;
- (void)mailComposeController:(id)arg1 didFinishWithResult:(int)arg2 error:(id)arg3;
- (_Bool)textViewShouldBeginEditing:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)hideProgressAndReport;
- (void)updateProgressText;
- (void)viewDidAppear:(_Bool)arg1;
- (void)addNetworkReportView;
- (void)postEmail;
- (void)goBack;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

