//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseViewController.h"

#import "MBProgressHUDDelegate-Protocol.h"
#import "PopUpInputViewDelegate-Protocol.h"
#import "SearchResultViewDelegate-Protocol.h"
#import "UISearchBarDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"

@class AFHTTPRequestOperation, BookItem, MBProgressHUD, NSArray, NSMutableArray, NSMutableDictionary, NSString, PopUpInputView, SearchResultView, UIButton, UIImageView, UISearchBar, UITableView, UIView;
@protocol SearchBookViewDelegate;

@interface SearchBookViewController : BaseViewController <UITextFieldDelegate, MBProgressHUDDelegate, UISearchBarDelegate, UITableViewDelegate, UITableViewDataSource, PopUpInputViewDelegate, SearchResultViewDelegate>
{
    BookItem *item;
    NSString *categoryName;
    UIImageView *navigationShadow;
    SearchResultView *searchResultView;
    PopUpInputView *addDescriptionView;
    NSString *selectedBookId;
    _Bool bookAlreadyAdded;
    MBProgressHUD *progress;
    UITableView *searchTextCompleteTable;
    NSArray *searchTextArr;
    double keyboradHeight;
    UISearchBar *m_searchBar;
    _Bool shouldHideAutoCompleteTable;
    _Bool isLoadHotWords;
    UITableView *searchDefaultTableView;
    NSMutableArray *aryHotWords;
    NSMutableArray *searchHistoryWords;
    NSMutableArray *currentAllHistoryWords;
    int totalCount;
    UIButton *sectionBtn;
    UIView *headerView;
    AFHTTPRequestOperation *operation;
    _Bool _fromBookListView;
    _Bool _needAccurateSearch;
    NSMutableDictionary *_bookListSearchItems;
    NSString *_searchText;
    id <SearchBookViewDelegate> _searchBookViewDelegate;
}

@property(nonatomic) __weak id <SearchBookViewDelegate> searchBookViewDelegate; // @synthesize searchBookViewDelegate=_searchBookViewDelegate;
@property(nonatomic) _Bool needAccurateSearch; // @synthesize needAccurateSearch=_needAccurateSearch;
@property(retain, nonatomic) NSString *searchText; // @synthesize searchText=_searchText;
@property(retain, nonatomic) NSMutableDictionary *bookListSearchItems; // @synthesize bookListSearchItems=_bookListSearchItems;
@property(nonatomic) _Bool fromBookListView; // @synthesize fromBookListView=_fromBookListView;
- (void).cxx_destruct;
- (void)goAdSwitchView;
- (void)goEventViewWithUrlStr:(id)arg1;
- (void)goToAddBookView;
- (void)goBack;
- (void)removeHistoryRecord:(id)arg1;
- (void)addHistoryRecord:(id)arg1;
- (void)getHistoryRecord;
- (void)onClickFirstRightItem;
- (void)onClickLeftItem;
- (void)searchResultCellSelected:(id)arg1;
- (void)confirmInputViewBtnClicked:(id)arg1;
- (void)hideInputViewFinished;
- (void)hideInputViewBtnClicked:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)searchTextSelectedWithIndexPath:(id)arg1;
- (void)hideSearchTextCompleteView;
- (void)showSearchTextCompleteView;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)searchBarCancelButtonClicked:(id)arg1;
- (void)searchBarTextDidEndEditing:(id)arg1;
- (void)searchBarTextDidBeginEditing:(id)arg1;
- (void)hideSearchResultView;
- (void)triggerSearchWithStr:(id)arg1;
- (void)searchBarSearchButtonClicked:(id)arg1;
- (void)onClickSearch:(id)arg1;
- (void)onClickRemoveHistory;
- (void)onClickChangeHotWords;
- (void)adaptDefaultTableHeaderView;
- (void)showSearchDefaultTableHeaderView;
- (void)viewDidUnload;
- (void)updateKeyboradHeight:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (id)createSearchBar;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

