//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface ShareSDK : NSObject
{
}

+ (void)share:(unsigned long long)arg1 parameters:(id)arg2 onStateChanged:(CDUnknownBlockType)arg3;
+ (void)getFriends:(unsigned long long)arg1 cursor:(unsigned long long)arg2 size:(unsigned long long)arg3 onStateChanged:(CDUnknownBlockType)arg4;
+ (void)addFriend:(unsigned long long)arg1 user:(id)arg2 onStateChanged:(CDUnknownBlockType)arg3;
+ (void)getUserInfo:(unsigned long long)arg1 conditional:(id)arg2 onStateChanged:(CDUnknownBlockType)arg3;
+ (void)getUserInfo:(unsigned long long)arg1 onStateChanged:(CDUnknownBlockType)arg2;
+ (void)cancelAuthorize:(unsigned long long)arg1;
+ (_Bool)hasAuthorized:(unsigned long long)arg1;
+ (void)authorize:(unsigned long long)arg1 settings:(id)arg2 onStateChanged:(CDUnknownBlockType)arg3;
+ (void)registerApp:(id)arg1 activePlatforms:(id)arg2 onImport:(CDUnknownBlockType)arg3 onConfiguration:(CDUnknownBlockType)arg4;

@end

