//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "MBProgressHUDDelegate-Protocol.h"
#import "SyncBookDelegate-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"

@class MBProgressHUD, NSString, UIView;
@protocol ShareSDKViewDelegate;

@interface ShareSDKUtils : NSObject <MBProgressHUDDelegate, UIActionSheetDelegate, SyncBookDelegate>
{
    MBProgressHUD *progress;
    UIView *hoverView;
    UIView *customLoginView;
    _Bool isShowTip;
    double loginViewHeight;
    _Bool _popStyle;
    id <ShareSDKViewDelegate> _shareSDKViewDelegate;
}

+ (id)sharedInstance;
@property(nonatomic) __weak id <ShareSDKViewDelegate> shareSDKViewDelegate; // @synthesize shareSDKViewDelegate=_shareSDKViewDelegate;
@property(nonatomic) _Bool popStyle; // @synthesize popStyle=_popStyle;
- (void).cxx_destruct;
- (void)syncBookFinished;
- (void)quickLoginClicked;
- (void)emailLoginViewClicked;
- (void)removeLoginView;
- (void)hideLoginView;
- (void)weixinAuth;
- (void)qqAuth;
- (void)sinaWeiboAuth;
- (void)showLoginViewWithTip:(id)arg1 withPopStyle:(_Bool)arg2 showTip:(_Bool)arg3;
- (void)showProgress:(id)arg1;
- (void)removeAuthData;
- (void)userLogoutForInvalidToken;
- (void)startRequestRemitAdInfo;
- (void)updateUserAccount;
- (void)getUserAccountWithProgress:(_Bool)arg1;
- (void)getUserInfoWithProgress:(_Bool)arg1;
- (void)mailLoginWithMail:(id)arg1 password:(id)arg2;
- (void)mailRegisterWithMail:(id)arg1 password:(id)arg2 nickname:(id)arg3;
- (void)quickLoginWithUsername:(id)arg1 password:(id)arg2;
- (void)quickRegisterWithUsername:(id)arg1 password:(id)arg2 nickname:(id)arg3;
- (void)userLogout;
- (void)userLogin:(id)arg1 loginType:(unsigned long long)arg2;
- (void)startUserExpRequestWithShareType:(int)arg1;
- (id)getShareChannelNameWithType:(unsigned long long)arg1;
- (void)shareMessageWithPlatformType:(unsigned long long)arg1 shareMessageItem:(id)arg2;
- (void)showAuthResult:(id)arg1;
- (void)getAuthentication:(unsigned long long)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

