//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface ShareMessageItem : NSObject
{
    int _bgColorTag;
    int _typeTag;
    NSString *_title;
    NSString *_message;
    NSString *_url;
    NSString *_image;
}

@property(nonatomic) int typeTag; // @synthesize typeTag=_typeTag;
@property(nonatomic) int bgColorTag; // @synthesize bgColorTag=_bgColorTag;
@property(retain, nonatomic) NSString *image; // @synthesize image=_image;
@property(retain, nonatomic) NSString *url; // @synthesize url=_url;
@property(retain, nonatomic) NSString *message; // @synthesize message=_message;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (void)setValue:(id)arg1 forUndefinedKey:(id)arg2;
- (id)initWithDictionary:(id)arg1;

@end

