//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableView.h>

#import "SingleBookNormalTopicListCellDelegate-Protocol.h"
#import "SingleBookReviewTopicListCellDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class AFHTTPRequestOperation, NSArray, NSMutableArray, NSMutableDictionary, NSString;
@protocol SingleBookTopicListTableViewDelegate;

@interface SingleBookTopicListTableView : UITableView <UITableViewDataSource, UITableViewDelegate, SingleBookReviewTopicListCellDelegate, SingleBookNormalTopicListCellDelegate>
{
    double didSelectedTime;
    NSMutableDictionary *cellHeightDic;
    _Bool _needBottomPadding;
    NSMutableArray *_topicListArr;
    NSArray *_bookIds;
    NSString *_lastTime;
    NSString *_token;
    NSString *_listType;
    NSString *_topicSort;
    AFHTTPRequestOperation *_requestCanCancel;
    long long _limitCount;
    id <SingleBookTopicListTableViewDelegate> _singleBookTopicListTableViewDelegate;
}

@property(nonatomic) __weak id <SingleBookTopicListTableViewDelegate> singleBookTopicListTableViewDelegate; // @synthesize singleBookTopicListTableViewDelegate=_singleBookTopicListTableViewDelegate;
@property(nonatomic) long long limitCount; // @synthesize limitCount=_limitCount;
@property(retain, nonatomic) AFHTTPRequestOperation *requestCanCancel; // @synthesize requestCanCancel=_requestCanCancel;
@property(retain, nonatomic) NSString *topicSort; // @synthesize topicSort=_topicSort;
@property(nonatomic) _Bool needBottomPadding; // @synthesize needBottomPadding=_needBottomPadding;
@property(retain, nonatomic) NSString *listType; // @synthesize listType=_listType;
@property(retain, nonatomic) NSString *token; // @synthesize token=_token;
@property(retain, nonatomic) NSString *lastTime; // @synthesize lastTime=_lastTime;
@property(retain, nonatomic) NSArray *bookIds; // @synthesize bookIds=_bookIds;
@property(retain, nonatomic) NSMutableArray *topicListArr; // @synthesize topicListArr=_topicListArr;
- (void).cxx_destruct;
- (void)SBNTL_avatarBtnClicked:(id)arg1;
- (void)SBRT_avatarBtnClicked:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)addCellHeightDataToDicWithLabel:(id)arg1 content:(id)arg2 row:(long long)arg3;
- (long long)parseToReviewTopicListItem:(id)arg1;
- (long long)parseToNormalTopicListItem:(id)arg1;
- (void)jsonParserForTopicList:(id)arg1 refresh:(_Bool)arg2;
- (void)loadTopicList:(_Bool)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

