//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SSDKContext.h"

#import "SSDKHandleOpenURLFilter-Protocol.h"

@class NSString;

@interface SSDKContext (Global) <SSDKHandleOpenURLFilter>
+ (void)initialize;
- (_Bool)application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4;
- (_Bool)application:(id)arg1 handleOpenURL:(id)arg2;
- (_Bool)handleOpenURL:(id)arg1 sourceApplication:(id)arg2 annotation:(id)arg3;
- (void)removeHandleOpenURLFilter:(id)arg1;
- (void)addHandleOpenURLFilter:(id)arg1;
- (void)unhookApplicationDelegate;
- (void)hookApplicationDelegate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

