//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "IMOBFPlugin-Protocol.h"

@class NSString;

@interface SSPEvernoteProxy : NSObject <IMOBFPlugin>
{
}

- (void)skipType:(unsigned long long)arg1 reader:(id)arg2;
- (id)notFoundErrorFieldMapper;
- (id)systemErrorFieldMapper;
- (id)userErrorFieldMapper;
- (id)applicationErrorWithReader:(id)arg1;
- (id)userFieldMapper;
- (id)noteFieldMapper;
- (id)parseSetDataWithReader:(id)arg1 fieldMapper:(id)arg2;
- (id)parseDictionaryDataWithReader:(id)arg1 fieldMapper:(id)arg2;
- (id)parseArrayDataWithReader:(id)arg1 fieldMapper:(id)arg2;
- (id)parseStructDataWithReader:(id)arg1 fieldMapper:(id)arg2;
- (id)parseValueWithReader:(id)arg1 fieldType:(unsigned long long)arg2 fieldMapper:(id)arg3;
- (id)requestWithUrlString:(id)arg1;
- (void)registerShareMethod;
- (void)registerGetUserInfoMethod;
- (void)unload;
- (void)load:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

