//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "IMOBFPlugin-Protocol.h"

@class NSString;

@interface SSPFacebookMessengerProxy : NSObject <IMOBFPlugin>
{
}

- (_Bool)canShare:(id)arg1 callback:(id)arg2;
- (void)registerShareMethod;
- (_Bool)isClientInstalled;
- (void)unload;
- (void)load:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

