//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, UIDocumentInteractionController;

@interface SSPWhatsAppShareObserver : NSObject
{
    _Bool _sent;
    UIDocumentInteractionController *_documentVC;
    NSString *_imagePath;
    NSString *_callback;
}

@property(copy, nonatomic) NSString *callback; // @synthesize callback=_callback;
@property(copy, nonatomic) NSString *imagePath; // @synthesize imagePath=_imagePath;
@property(nonatomic) _Bool sent; // @synthesize sent=_sent;
@property(retain, nonatomic) UIDocumentInteractionController *documentVC; // @synthesize documentVC=_documentVC;
- (void).cxx_destruct;

@end

