//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class AFHTTPRequestOperation, NSOperationQueue, NSString;
@protocol SyncBookDelegate;

@interface SyncBook : NSObject
{
    AFHTTPRequestOperation *requestCanCancel;
    NSString *userId;
    NSString *token;
    NSOperationQueue *subscribeOperationQueue;
    id <SyncBookDelegate> _delegate;
}

+ (id)sharedInstance;
@property(nonatomic) __weak id <SyncBookDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)sendAsyncRequest:(id)arg1 bookId:(id)arg2 delete:(_Bool)arg3 isAll:(_Bool)arg4;
- (void)deleteBookIds;
- (void)uploadBookIds:(_Bool)arg1;
- (void)hudWasHiddenByCancelBtn;
- (void)cancelSyncBook;
- (id)changeArrayToString:(id)arg1;
- (void)uploadLocalFeedingBooks;
- (void)uploadLocalBooks;
- (void)unsubscribeToServer:(id)arg1;
- (void)subscribeToServer:(id)arg1;
- (_Bool)localDateOlderThanServerDate:(id)arg1 syncItem:(id)arg2 bookItem:(id)arg3;
- (id)getAllFeedBookDic;
- (void)mergeFeededBooksWithData:(id)arg1 serverSyncDate:(id)arg2;
- (void)mergeServerBooksToLocalWithData:(id)arg1 serverSyncDate:(id)arg2;
- (void)addNotExistInServerBookIdsToArray:(id)arg1 withServerBookIds:(id)arg2 serverSyncDate:(id)arg3;
- (void)addOtherUserBookIdsToArray:(id)arg1;
- (void)deleteLocalBooksWithData:(id)arg1 serverSyncDate:(id)arg2;
- (id)getCurrentUserLocalBookIds;
- (void)updateLocalBooksSyncDateWithData:(id)arg1;
- (id)getFormattedDataWithNormalData:(id)arg1 feedData:(id)arg2;
- (void)syncBookRequestWithServerSyncTime:(id)arg1;
- (void)updateLocalBookshelfSyncTime:(id)arg1;
- (id)getLocalBookshelfSyncTime;
- (id)syncLogInitialize;
- (id)getNeedDeleteUserIdBookRenovateLog;
- (id)getBookRenovateLogWithoutAlreadySync;
- (void)startSyncBookWithProgress:(_Bool)arg1;
- (void)startSyncNotificationBookshelf;
- (void)markSyncBookNotNeeded;
- (void)markSyncBookNeeded;
- (void)startSyncBookInBackground;
- (id)init;

@end

