//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface SyncItem : NSObject
{
    _Bool _deleted;
    NSString *_bookId;
    NSString *_lastLoggedTime;
    NSString *_account;
}

@property(nonatomic) _Bool deleted; // @synthesize deleted=_deleted;
@property(retain, nonatomic) NSString *account; // @synthesize account=_account;
@property(retain, nonatomic) NSString *lastLoggedTime; // @synthesize lastLoggedTime=_lastLoggedTime;
@property(retain, nonatomic) NSString *bookId; // @synthesize bookId=_bookId;
- (void).cxx_destruct;
- (id)description;
- (id)init;

@end

