//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol TraceRouteDelegate;

@interface TraceRouteUtils : NSObject
{
    _Bool reportFinished;
    id <TraceRouteDelegate> _delegate;
}

@property(nonatomic) __weak id <TraceRouteDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (char *)inet_ntoay:(unsigned long long)arg1 ip:(char *)arg2;
- (int)check_packet:(char *)arg1 buflen:(int)arg2;
- (int)recv_tracert:(int)arg1 srcaddr:(struct sockaddr_in *)arg2 buf:(char *)arg3 buflen:(int)arg4;
- (_Bool)send_tracert:(int)arg1 dstaddr:(struct sockaddr_in *)arg2 ttl:(int)arg3;
- (void)munuallyFinishReport;
- (void)startTraceRoute:(id)arg1;
- (void)unpack:(char *)arg1 len:(int)arg2;
- (int)recv_packet;
- (int)send_packet;
- (int)pack:(int)arg1;
- (void)startPing:(id)arg1;
- (id)getWANIP;
- (void)triggerDelegateWithString:(id)arg1;
- (void)stopReport;
- (void)startReport;

@end

