//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionView.h>

@interface UICollectionView (IMStrandCollectionViewAdapter)
- (void)im_moveItemAtIndexPath:(id)arg1 toIndexPath:(id)arg2;
- (void)im_reloadItemsAtIndexPaths:(id)arg1;
- (void)im_deleteItemsAtIndexPaths:(id)arg1;
- (void)im_insertItemsAtIndexPaths:(id)arg1;
- (void)im_moveSection:(long long)arg1 toSection:(long long)arg2;
- (void)im_reloadSections:(id)arg1;
- (void)im_deleteSections:(id)arg1;
- (void)im_insertSections:(id)arg1;
- (void)im_scrollToItemAtIndexPath:(id)arg1 atScrollPosition:(unsigned long long)arg2 animated:(_Bool)arg3;
- (id)im_indexPathsForVisibleItems;
- (id)im_visibleCells;
- (id)im_cellForItemAtIndexPath:(id)arg1;
- (id)im_indexPathForCell:(id)arg1;
- (id)im_indexPathForItemAtPoint:(struct CGPoint)arg1;
- (id)im_layoutAttributesForItemAtIndexPath:(id)arg1;
- (void)im_reloadData;
- (void)im_deselectItemAtIndexPath:(id)arg1 animated:(_Bool)arg2;
- (void)im_selectItemAtIndexPath:(id)arg1 animated:(_Bool)arg2 scrollPosition:(unsigned long long)arg3;
- (id)im_indexPathsForSelectedItems;
- (id)im_dequeueReusableCellWithReuseIdentifier:(id)arg1 forIndexPath:(id)arg2;
- (id)im_dataSource;
- (void)im_setDataSource:(id)arg1;
- (id)im_delegate;
- (void)im_setDelegate:(id)arg1;
- (id)im_strandAdapter;
- (void)im_setStrandAdapter:(id)arg1;
@end

