//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableView.h>

@interface UITableView (IMStrandTableViewAdapter)
- (id)im_dequeueReusableCellWithIdentifier:(id)arg1 forIndexPath:(id)arg2;
- (void)im_deselectRowAtIndexPath:(id)arg1 animated:(_Bool)arg2;
- (void)im_selectRowAtIndexPath:(id)arg1 animated:(_Bool)arg2 scrollPosition:(long long)arg3;
- (id)im_indexPathsForSelectedRows;
- (id)im_indexPathForSelectedRow;
- (void)im_moveRowAtIndexPath:(id)arg1 toIndexPath:(id)arg2;
- (void)im_reloadRowsAtIndexPaths:(id)arg1 withRowAnimation:(long long)arg2;
- (void)im_deleteRowsAtIndexPaths:(id)arg1 withRowAnimation:(long long)arg2;
- (void)im_insertRowsAtIndexPaths:(id)arg1 withRowAnimation:(long long)arg2;
- (void)im_moveSection:(long long)arg1 toSection:(long long)arg2;
- (void)im_reloadSections:(id)arg1 withRowAnimation:(long long)arg2;
- (void)im_deleteSections:(id)arg1 withRowAnimation:(long long)arg2;
- (void)im_insertSections:(id)arg1 withRowAnimation:(long long)arg2;
- (void)im_endUpdates;
- (void)im_beginUpdates;
- (void)im_scrollToRowAtIndexPath:(id)arg1 atScrollPosition:(long long)arg2 animated:(_Bool)arg3;
- (id)im_indexPathsForVisibleRows;
- (id)im_visibleCells;
- (id)im_cellForRowAtIndexPath:(id)arg1;
- (id)im_indexPathsForRowsInRect:(struct CGRect)arg1;
- (id)im_indexPathForCell:(id)arg1;
- (id)im_indexPathForRowAtPoint:(struct CGPoint)arg1;
- (struct CGRect)im_rectForRowAtIndexPath:(id)arg1;
- (void)im_reloadData;
- (id)im_dataSource;
- (void)im_setDataSource:(id)arg1;
- (id)im_delegate;
- (void)im_setDelegate:(id)arg1;
- (id)im_strandAdapter;
- (void)im_setStrandAdapter:(id)arg1;
@end

