//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseViewController.h"

@class NSMutableArray;

@interface WeChatPublicViewController : BaseViewController
{
    NSMutableArray *dataArray;
    _Bool _isFromReadingView;
}

@property(nonatomic) _Bool isFromReadingView; // @synthesize isFromReadingView=_isFromReadingView;
- (void).cxx_destruct;
- (void)onClickLeftItem;
- (void)didReceiveMemoryWarning;
- (void)openWeChat;
- (id)attrStrWithString:(id)arg1 color:(id)arg2 fontSize:(double)arg3;
- (void)viewDidLoad;
- (void)loadView;

@end

