//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIResponder.h>

#import "AppPageViewDelegate-Protocol.h"
#import "CustomAdUtilsDelegate-Protocol.h"
#import "CustomSplashAdUtilsDelegate-Protocol.h"
#import "MBProgressHUDDelegate-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"
#import "UIApplicationDelegate-Protocol.h"

@class AppPageViewController, AppRootViewController, BookShelfAdItem, MBProgressHUD, NSDictionary, NSString, TopicDetailItem, UIButton, UIView, UIWindow, YouShaQiViewController;

@interface YouShaQiAppDelegate : UIResponder <MBProgressHUDDelegate, AppPageViewDelegate, UIActionSheetDelegate, UIApplicationDelegate, CustomAdUtilsDelegate, CustomSplashAdUtilsDelegate>
{
    MBProgressHUD *progress;
    TopicDetailItem *detailItem;
    AppRootViewController *rootView;
    AppPageViewController *pageView;
    YouShaQiViewController *viewController;
    UIView *hoverView;
    UIView *customRateView;
    NSDictionary *currentUserInfo;
    _Bool splashViewAlreadySetted;
    UIButton *listSplashView;
    BookShelfAdItem *splashAdItem;
    UIView *bottomView;
    UIView *topAdView;
    NSDictionary *inmobiSplashAdDic;
    UIWindow *_window;
}

@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
- (void).cxx_destruct;
- (void)remoteControlReceivedWithEvent:(id)arg1;
- (void)customAdUtilsInmobiSplashAdSucceed;
- (void)customAdUtilsBaiduSplashAdClicked:(id)arg1;
- (void)customAdUtilsBaiduSplashAdSucceed:(id)arg1;
- (void)customAdUtilsGDTSplashAdSucceed;
- (void)customAdUtilsGDTSplashAdStarted:(id)arg1;
- (void)onClickNativeAd:(id)arg1;
- (id)stripBookIdFromTopicStr:(id)arg1;
- (void)AppPageViewDidDismissed;
- (void)startupAnimationDone:(id)arg1 finished:(id)arg2 context:(void *)arg3;
- (void)hideSplashView:(id)arg1;
- (id)addSplashBottomView:(id)arg1;
- (id)createSplashTopAdView;
- (void)createSplashViewWithUserInfo:(id)arg1 splashDic:(id)arg2;
- (unsigned long long)application:(id)arg1 supportedInterfaceOrientationsForWindow:(id)arg2;
- (void)applicationWillTerminate:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)applicationDidReceiveMemoryWarning:(id)arg1;
- (_Bool)application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4;
- (void)showRemoteNotification:(id)arg1;
- (void)application:(id)arg1 didReceiveRemoteNotification:(id)arg2;
- (void)application:(id)arg1 didFailToRegisterForRemoteNotificationsWithError:(id)arg2;
- (void)application:(id)arg1 didRegisterForRemoteNotificationsWithDeviceToken:(id)arg2;
- (void)application:(id)arg1 didRegisterUserNotificationSettings:(id)arg2;
- (void)setupIFlySDK;
- (void)startUserInfoRequest;
- (void)startUserExpRequest;
- (void)setupRemoteNotification;
- (void)enterWithPageView;
- (void)parseUserAuthorityDataToObject:(id)arg1;
- (void)loadUserAuthority;
- (void)parseJsonDataToObject:(id)arg1;
- (void)loadRewardData;
- (void)setupNavigationController:(id)arg1 launchFromNotification:(_Bool)arg2;
- (void)startSendLocalReceipt:(id)arg1 receipt:(id)arg2 productId:(id)arg3;
- (void)startUnSendReciptRequest;
- (void)updateGlobalUserAgentWithStr:(id)arg1;
- (id)concatParamWithOriginStr:(id)arg1;
- (void)updateUmengSpecialParams:(id)arg1;
- (void)uMengOnlineConfigCallBack:(id)arg1;
- (void)getUMengOnlineConfig;
- (void)setupUmengTrack;
- (void)getSeverErrorConfig;
- (void)setupShareSDK;
- (void)setupCache;
- (void)setNewResourceForOldUser;
- (void)changeOldReadModeToNew;
- (void)parameterInitial;
- (void)getVersionLimitConfig;
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

